        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      RESET ; Reset               ; Int 08h (IRQ 0)
        dd      TICK ; Tick                ; Int 09h (IRQ 1)
        dd      KEY ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      GAME_OVER ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      NEW_PIECE ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      RECEIVED ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      TOUCHDOWN ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      CLEAR ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84
        align	2
SlidePiece:	; void SlidePiece(int ID, int direction)
	push	bp
	mov	bp, sp
	push	ax
	push	dx
 	mov	ah, 0		; Slide piece operation
  	mov	al, [bp+6]	; Move direction (loword only)
	mov	dx, [bp+4]	; Move id
	int	1Bh		; Call Simptris services
	pop	dx
	pop	ax
	pop	bp
	ret
RotatePiece:	; void RotatePiece(int ID, int direction)
	push	bp
	mov	bp, sp
	push	ax
	push	dx
 	mov	ah, 1		; Rotate piece operation
 	mov	al, [bp+6]	; Move direction (loword only)
	mov	dx, [bp+4]	; Move id
	int	1Bh		; Call Simptris services
	pop	dx
	pop	ax
	pop	bp
	ret
SeedSimptris:	; void SeedSimptris(long seed)
	push	bp
	mov	bp, sp
	push	ax
	push	cx
	push    dx
 	mov	ah, 2		; Seed operation
	mov	dx, [bp+4]	; Move loword of seed
	mov	cx, [bp+6]	; Move hiword of seed
	int	1Bh		; Call Simptris services
	pop	dx
	pop	cx
	pop	ax
	pop	bp
	ret
StartSimptris:	; void StartSimptris(void)
	push	ax
 	mov	ah, 3		; Start Simptris operation
	int	1Bh		; Call Simptris services
	pop	ax
	ret
; ISR file
;1 Save the context of whatever was running by pushing all registers onto the stack, except SP, SS, CS, IP, and the flags.
;2 Enable interrupts to allow higher priority IRQs to interrupt.
;3 Run the interrupt handler, which is usually a C function that does the work for this interrupt.
;4 Disable interrupts.
;5 Send the EOI command to the PIC, informing it that the handler is finished.
;6 Restore the context of what was running before the interrupt occurred by popping the registers saved in step 1 off the stack.
;7 Execute the iret instruction. This restores in one atomic operation the values for IP, CS, and the flags, which were automatically -
;	; - saved on the stack by the processor when the interrupt occurred. This effectively restores execution to the point where the interrupt occurred.

RESET:
	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

	call YKEnterISR

	sti
	call c_reset_handler
	cli

	mov al, 0x20        ; send eoi to pic
	out 0x20, al        ; send eoi to pic

	call YKExitISR

	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret


KEY:

	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

        mov ax, [YKISRDepth]          ;save the depth counter
	cmp ax, 0                     ; check if the depth is zero, if it is save the SP of the task we are interupting
	jnz key_not_lowest_interrupt  ; skip saving the stack because we are not interupting that task

	mov bx, [YKRdyList] ; save the sp
	mov [bx], sp

key_not_lowest_interrupt:
	call YKEnterISR

	sti                 ; enable interrupts for higher priority IRQs ?
	call c_key_handler  ; run
	cli                 ; disable interrupts ?

	mov al, 0x20        ; send eoi to pic
	out 0x20, al        ; send eoi to pic

	call YKExitISR

	;restore reg
	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret

TICK:
	; save reg
	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

  mov ax, [YKISRDepth] ;save the depth counter
	cmp ax, 0            ; check if the depth is zero, if it is save the SP of the task we are interupting
	jnz not_lowest_interrupt


	mov bx, [YKRdyList] ; save SP of interupted task
	mov [bx], sp

not_lowest_interrupt:
	call YKEnterISR

	sti                 ; enable interrupts for higher priority IRQs ?

	;call YKTickHandler;
	call c_tick_handler ; run interrupt handler ? I think this is the c file

	cli                 ; disable interrupts

	mov al, 0x20        ; send eoi to pic
	out 0x20, al        ; send eoi to pic

	call YKExitISR

	;restore
	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret
	
	
	
	
	
	
GAME_OVER:
	; save context
	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

	mov ax, [YKISRDepth]
	cmp ax, 0
	jnz game_over_not_lowest_interrupt

	mov bx, [YKRdyList]
	mov [bx], sp

game_over_not_lowest_interrupt:
	call YKEnterISR

	sti 
	call c_game_over_handler 
	cli 

	mov	al, 0x20 
	out	0x20, al

	call YKExitISR

	pop es	
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret 


NEW_PIECE:
	push ax 
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es


	mov ax, [YKISRDepth]
	cmp ax, 0
	jnz new_piece_not_lowest_interrupt

	mov bx, [YKRdyList]
	mov [bx], sp

new_piece_not_lowest_interrupt:
	call YKEnterISR

	sti 
	call c_new_piece_handler 
	cli 

	mov	al, 0x20 
	out	0x20, al
	
	call YKExitISR

	pop es	
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret 

RECEIVED:
	push ax 
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

	mov ax, [YKISRDepth]
	cmp ax, 0
	jnz received_not_lowest_interrupt

	mov bx, [YKRdyList]
	mov [bx], sp

received_not_lowest_interrupt:

	call YKEnterISR

	sti ;
	call c_received_handler ; 
	cli ; 
	
	mov	al, 0x20
	out	0x20, al	

	call YKExitISR

	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret


TOUCHDOWN:

	mov	al, 0x20
	out	0x20, al	

	iret


CLEAR:

	mov	al, 0x20
	out	0x20, al	

	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
c_reset_handler:
	; >>>>> Line:	15
	; >>>>> void c_reset_handler(){ 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	16
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
	ALIGN	2
c_tick_handler:
	; >>>>> Line:	19
	; >>>>> void c_tick_handler(){ 
	jmp	L_myinth_4
L_myinth_5:
	; >>>>> Line:	20
	; >>>>> YKTickHandler(); 
	call	YKTickHandler
	mov	sp, bp
	pop	bp
	ret
L_myinth_4:
	push	bp
	mov	bp, sp
	jmp	L_myinth_5
L_myinth_8:
	DB	") IGNORED",0xA,0
L_myinth_7:
	DB	0xA,"KEYPRESS (",0
	ALIGN	2
c_key_handler:
	; >>>>> Line:	23
	; >>>>> void c_key_handler(){ 
	jmp	L_myinth_9
L_myinth_10:
	; >>>>> Line:	25
	; >>>>> c = KeyBuffer; 
	mov	al, byte [KeyBuffer]
	mov	byte [bp-1], al
	; >>>>> Line:	27
	; >>>>> print("\nKEYPRESS (", 11); 
	mov	ax, 11
	push	ax
	mov	ax, L_myinth_7
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	28
	; >>>>> printChar(c); 
	push	word [bp-1]
	call	printChar
	add	sp, 2
	; >>>>> Line:	29
	; >>>>> print(") IGNORED\n", 10); 
	mov	ax, 10
	push	ax
	mov	ax, L_myinth_8
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_myinth_9:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_10
L_myinth_12:
	DB	0xA,"GAME OVER",0xA,0
	ALIGN	2
c_game_over_handler:
	; >>>>> Line:	32
	; >>>>> void c_game_over_handler(void){ 
	jmp	L_myinth_13
L_myinth_14:
	; >>>>> Line:	33
	; >>>>>  
	mov	ax, L_myinth_12
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	34
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_13:
	push	bp
	mov	bp, sp
	jmp	L_myinth_14
	ALIGN	2
L_myinth_16:
	DW	0
	ALIGN	2
c_new_piece_handler:
	; >>>>> Line:	37
	; >>>>> void c_new_piece_handler(void){ 
	jmp	L_myinth_17
L_myinth_18:
	; >>>>> Line:	39
	; >>>>> newPieceList[i].id = NewPieceID; 
	mov	ax, word [L_myinth_16]
	mov	cx, 3
	shl	ax, cl
	mov	si, ax
	add	si, newPieceList
	mov	ax, word [NewPieceID]
	mov	word [si], ax
	; >>>>> Line:	40
	; >>>>> newPieceList[i].type = NewPieceType; 
	mov	ax, word [L_myinth_16]
	mov	cx, 3
	shl	ax, cl
	add	ax, newPieceList
	mov	si, ax
	add	si, 2
	mov	ax, word [NewPieceType]
	mov	word [si], ax
	; >>>>> Line:	41
	; >>>>> newPieceList[i].orient = NewPieceOrientation; 
	mov	ax, word [L_myinth_16]
	mov	cx, 3
	shl	ax, cl
	add	ax, newPieceList
	mov	si, ax
	add	si, 4
	mov	ax, word [NewPieceOrientation]
	mov	word [si], ax
	; >>>>> Line:	42
	; >>>>> newPieceList[i].col = NewPieceColumn; 
	mov	ax, word [L_myinth_16]
	mov	cx, 3
	shl	ax, cl
	add	ax, newPieceList
	mov	si, ax
	add	si, 6
	mov	ax, word [NewPieceColumn]
	mov	word [si], ax
	; >>>>> Line:	44
	; >>>>> YKQPost(newPieceQueue, (void *) &(newPieceList[i])); 
	mov	ax, word [L_myinth_16]
	mov	cx, 3
	shl	ax, cl
	add	ax, newPieceList
	push	ax
	push	word [newPieceQueue]
	call	YKQPost
	add	sp, 4
	; >>>>> Line:	45
	; >>>>> i++; 
	inc	word [L_myinth_16]
	; >>>>> Line:	46
	; >>>>> if(i == 50){ 
	cmp	word [L_myinth_16], 50
	jne	L_myinth_19
	; >>>>> Line:	47
	; >>>>> i = 0; 
	mov	word [L_myinth_16], 0
L_myinth_19:
	mov	sp, bp
	pop	bp
	ret
L_myinth_17:
	push	bp
	mov	bp, sp
	jmp	L_myinth_18
	ALIGN	2
c_received_handler:
	; >>>>> Line:	51
	; >>>>> void c_received_handler(void){ 
	jmp	L_myinth_21
L_myinth_22:
	; >>>>> Line:	52
	; >>>>> YKSemPost(movePieceSem); 
	push	word [movePieceSem]
	call	YKSemPost
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_21:
	push	bp
	mov	bp, sp
	jmp	L_myinth_22
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
run_flag:
	DB	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	29
	; >>>>> void YKInitialize(void){ 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	31
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	32
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	33
	; >>>>> TKCurrentlyRunning = 0; 
	mov	word [TKCurrentlyRunning], 0
	; >>>>> Line:	34
	; >>>>> YKISRDepth = 0; 
	mov	word [YKISRDepth], 0
	; >>>>> Line:	35
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	37
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	39
	; >>>>> YKAvailTCBList = &(YKTCBArray[0]); 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	41
	; >>>>> for (i = 0; i < 9; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	42
	; >>>>> YKTCBArray[i].next = &(YKTCBArray[i+1]); 
	mov	ax, word [bp-2]
	inc	ax
	mov	cx, 22
	imul	cx
	add	ax, YKTCBArray
	push	ax
	mov	ax, word [bp-2]
	mov	cx, 22
	imul	cx
	mov	dx, ax
	add	dx, YKTCBArray
	mov	si, dx
	add	si, 8
	pop	ax
	mov	word [si], ax
L_yakc_6:
	inc	word [bp-2]
L_yakc_4:
	cmp	word [bp-2], 9
	jl	L_yakc_3
L_yakc_5:
	; >>>>> Line:	44
	; >>>>> YKTCBArray[9].next = 0; 
	mov	word [(206+YKTCBArray)], 0
	; >>>>> Line:	47
	; >>>>> for (i = 0; i < 10; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_8
L_yakc_7:
	; >>>>> Line:	48
	; >>>>> YKSemArray[i].val = -10; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	si, ax
	add	si, YKSemArray
	mov	word [si], -10
	; >>>>> Line:	49
	; >>>>> YKSemArray[i].active = 0; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	50
	; >>>>> YKSemArray[i].id = i; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_10:
	inc	word [bp-2]
L_yakc_8:
	cmp	word [bp-2], 10
	jl	L_yakc_7
L_yakc_9:
	; >>>>> Line:	53
	; >>>>> for (i = 0; i < 5; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_12
L_yakc_11:
	; >>>>> Line:	54
	; >>>>> CBptr tmp, 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	mov	si, ax
	add	si, YKQueueArray
	mov	word [si], 0
	; >>>>> Line:	55
	; >>>>> YKQueueArray[i].cur_length = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	56
	; >>>>> YKQueueArray[i].base_addr = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	57
	; >>>>> YKQueueArray[i].head = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	58
	; >>>>> YKQueueArray[i].tail = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 8
	mov	word [si], 0
L_yakc_14:
	inc	word [bp-2]
L_yakc_12:
	cmp	word [bp-2], 5
	jl	L_yakc_11
L_yakc_13:
	; >>>>> Line:	61
	; >>>>> for (i = 0; i < 5; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_16
L_yakc_15:
	; >>>>> Line:	62
	; >>>>> YKEVENTArray[i].active = 0; 
	mov	ax, word [bp-2]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, YKEVENTArray
	mov	word [si], 0
	; >>>>> Line:	63
	; >>>>> YKEVENTArray[i].flag = 0; 
	mov	ax, word [bp-2]
	shl	ax, 1
	shl	ax, 1
	add	ax, YKEVENTArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
L_yakc_18:
	inc	word [bp-2]
L_yakc_16:
	cmp	word [bp-2], 5
	jl	L_yakc_15
L_yakc_17:
	; >>>>> Line:	67
	; >>>>> YKNewTask(YKIdleTask, (void*)&idleStack[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (idleStack+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	70
	; >>>>> void YKIdleTask(void){ 
	jmp	L_yakc_20
L_yakc_21:
	; >>>>> Line:	71
	; >>>>> while(1){ 
	jmp	L_yakc_23
L_yakc_22:
	; >>>>> Line:	72
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	73
	; >>>>> YKIdleCount=YKIdleCount+1; 
	mov	ax, word [YKIdleCount]
	inc	ax
	mov	word [YKIdleCount], ax
	; >>>>> Line:	74
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_23:
	jmp	L_yakc_22
L_yakc_24:
	mov	sp, bp
	pop	bp
	ret
L_yakc_20:
	push	bp
	mov	bp, sp
	jmp	L_yakc_21
	ALIGN	2
YKNewTask:
	; >>>>> Line:	78
	; >>>>> void YKNewTask( void (*task)(void), void *taskStack, unsigned char priority){ 
	jmp	L_yakc_26
L_yakc_27:
	; >>>>> Line:	82
	; >>>>> taskStack = ((int *)taskStack) - 1; 
	mov	ax, word [bp+6]
	sub	ax, 2
	mov	word [bp+6], ax
	; >>>>> Line:	85
	; >>>>> tmp = YKAvailTCBList; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	; >>>>> Line:	86
	; >>>>> YKAvailTCBList = tmp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKAvailTCBList], ax
	; >>>>> Line:	88
	; >>>>> tmp->priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	89
	; >>>>> tmp->delay = 0; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	91
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	93
	; >>>>> if (YKRdyList == 0){ 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakc_28
	; >>>>> Line:	94
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	; >>>>> Line:	95
	; >>>>> tmp->next = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	96
	; >>>>> tmp->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	jmp	L_yakc_29
L_yakc_28:
	; >>>>> Line:	99
	; >>>>> tmp2 = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	100
	; >>>>> while (tmp2->priority < tmp->priority){ 
	jmp	L_yakc_31
L_yakc_30:
	; >>>>> Line:	101
	; >>>>> tmp2 = tmp2->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_31:
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-2]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_30
L_yakc_32:
	; >>>>> Line:	103
	; >>>>> if (tmp2->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_33
	; >>>>> Line:	104
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_34
L_yakc_33:
	; >>>>> Line:	107
	; >>>>> tmp2->prev->next = tmp; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_34:
	; >>>>> Line:	109
	; >>>>> tmp->prev = tmp2->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	110
	; >>>>> tmp->next  
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	111
	; >>>>> tmp2->prev = tmp; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_29:
	; >>>>> Line:	115
	; >>>>> tmp->stackptr = taskStack; 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	118
	; >>>>> tmp->stackptr = tmp->stackptr - 11; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, 22
	mov	word [si], ax
	; >>>>> Line:	119
	; >>>>> for(i=11; i>=0;i--){ 
	mov	word [bp-6], 11
	jmp	L_yakc_36
L_yakc_35:
	; >>>>> Line:	120
	; >>>>> if(i == 11){ 
	cmp	word [bp-6], 11
	jne	L_yakc_39
	; >>>>> Line:	121
	; >>>>> *(tmp->stackptr+i) = 0x200; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 512
	jmp	L_yakc_40
L_yakc_39:
	; >>>>> Line:	123
	; >>>>> else if(i == 10){ 
	cmp	word [bp-6], 10
	jne	L_yakc_41
	; >>>>> Line:	124
	; >>>>> *(tmp->stackptr+i) = 0; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 0
	jmp	L_yakc_42
L_yakc_41:
	; >>>>> Line:	126
	; >>>>> else if(i == 9){ 
	cmp	word [bp-6], 9
	jne	L_yakc_43
	; >>>>> Line:	127
	; >>>>> *(tmp->stackptr+i) = (int)task; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	ax, word [bp+4]
	mov	word [si], ax
	jmp	L_yakc_44
L_yakc_43:
	; >>>>> Line:	130
	; >>>>> *(tmp->stackptr+i) = 0; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 0
L_yakc_44:
L_yakc_42:
L_yakc_40:
L_yakc_38:
	dec	word [bp-6]
L_yakc_36:
	cmp	word [bp-6], 0
	jge	L_yakc_35
L_yakc_37:
	; >>>>> Line:	135
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_26:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_27
L_yakc_46:
	DB	"Start Run and call scheduler",0xA,0
	ALIGN	2
YKRun:
	; >>>>> Line:	138
	; >>>>> void YKRun(void){ 
	jmp	L_yakc_47
L_yakc_48:
	; >>>>> Line:	139
	; >>>>> printString("Start Run and call scheduler\n"); 
	mov	ax, L_yakc_46
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	140
	; >>>>> run_flag = 1; 
	mov	byte [run_flag], 1
	; >>>>> Line:	141
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_47:
	push	bp
	mov	bp, sp
	jmp	L_yakc_48
	ALIGN	2
YKScheduler:
	; >>>>> Line:	144
	; >>>>> ity_task->stackptr); 
	jmp	L_yakc_50
L_yakc_51:
	; >>>>> Line:	148
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	150
	; >>>>> highest_priority_task = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	151
	; >>>>> currentlyRunning = TKCurrentlyRunning; 
	mov	ax, word [TKCurrentlyRunning]
	mov	word [bp-4], ax
	; >>>>> Line:	153
	; >>>>> if(!run_flag || (TKCurrentlyRunning == highest_priority_task)){ 
	mov	al, byte [run_flag]
	test	al, al
	je	L_yakc_53
	mov	ax, word [bp-2]
	cmp	ax, word [TKCurrentlyRunning]
	jne	L_yakc_52
L_yakc_53:
	; >>>>> Line:	154
	; >>>>> return; 
	jmp	L_yakc_54
L_yakc_52:
	; >>>>> Line:	157
	; >>>>> YKCtxSwCount = YKCtxSwCount + 1; 
	mov	ax, word [YKCtxSwCount]
	inc	ax
	mov	word [YKCtxSwCount], ax
	; >>>>> Line:	158
	; >>>>> TKCurrentlyRunning = highest_priority_task; 
	mov	ax, word [bp-2]
	mov	word [TKCurrentlyRunning], ax
	; >>>>> Line:	159
	; >>>>> if(!save_flag){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_55
	; >>>>> Line:	160
	; >>>>> YKDispatcherNSave(highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	call	YKDispatcherNSave
	add	sp, 2
	jmp	L_yakc_56
L_yakc_55:
	; >>>>> Line:	163
	; >>>>> YKDispatcherSave(&(currentlyRunning->stackptr), highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	push	word [bp-4]
	call	YKDispatcherSave
	add	sp, 4
L_yakc_56:
L_yakc_54:
	mov	sp, bp
	pop	bp
	ret
L_yakc_50:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_51
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	167
	; >>>>> void  
	jmp	L_yakc_58
L_yakc_59:
	; >>>>> Line:	169
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	171
	; >>>>> if(count == 0){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_60
	; >>>>> Line:	172
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	173
	; >>>>> return; 
	jmp	L_yakc_61
L_yakc_60:
	; >>>>> Line:	176
	; >>>>> ready = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	177
	; >>>>> YKRdyList = ready->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	178
	; >>>>> ready->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	180
	; >>>>> ready->next = YKDelayList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKDelayList]
	mov	word [si], ax
	; >>>>> Line:	181
	; >>>>> YKDelayList = ready; 
	mov	ax, word [bp-2]
	mov	word [YKDelayList], ax
	; >>>>> Line:	182
	; >>>>> ready->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	183
	; >>>>> if(ready->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_62
	; >>>>> Line:	184
	; >>>>> ready->next->prev=ready; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_62:
	; >>>>> Line:	186
	; >>>>> ready->delay = count; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	187
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	188
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_61:
	mov	sp, bp
	pop	bp
	ret
L_yakc_58:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_59
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	192
	; >>>>> void YKEnterISR(void){ 
	jmp	L_yakc_64
L_yakc_65:
	; >>>>> Line:	193
	; >>>>> YKISRDepth = YKISRDepth + 1; 
	mov	ax, word [YKISRDepth]
	inc	ax
	mov	word [YKISRDepth], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_64:
	push	bp
	mov	bp, sp
	jmp	L_yakc_65
	ALIGN	2
YKExitISR:
	; >>>>> Line:	196
	; >>>>> void YKExitISR(void){ 
	jmp	L_yakc_67
L_yakc_68:
	; >>>>> Line:	197
	; >>>>> YKISRDepth = YKISRDepth - 1; 
	mov	ax, word [YKISRDepth]
	dec	ax
	mov	word [YKISRDepth], ax
	; >>>>> Line:	198
	; >>>>> if(YKISRDepth ==  
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_69
	; >>>>> Line:	199
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_69:
	mov	sp, bp
	pop	bp
	ret
L_yakc_67:
	push	bp
	mov	bp, sp
	jmp	L_yakc_68
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	203
	; >>>>> void YKTickHandler(void){ 
	jmp	L_yakc_71
L_yakc_72:
	; >>>>> Line:	205
	; >>>>> tempDelay = YKDelayList; 
	mov	ax, word [YKDelayList]
	mov	word [bp-2], ax
	; >>>>> Line:	206
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	208
	; >>>>> YKTickNum = YKTickNum + 1; 
	mov	ax, word [YKTickNum]
	inc	ax
	mov	word [YKTickNum], ax
	; >>>>> Line:	210
	; >>>>> while(tempDelay != 0){ 
	jmp	L_yakc_74
L_yakc_73:
	; >>>>> Line:	211
	; >>>>> tempNext = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
	; >>>>> Line:	212
	; >>>>> tempDelay->delay = tempDelay->delay - 1; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [si]
	dec	ax
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], ax
	; >>>>> Line:	213
	; >>>>> if(tempDelay->delay <= 0){ 
	mov	si, word [bp-2]
	add	si, 6
	cmp	word [si], 0
	jg	L_yakc_76
	; >>>>> Line:	214
	; >>>>> if(tempDelay->prev == 0){ 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_77
	; >>>>> Line:	215
	; >>>>> YKDelayList = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKDelayList], ax
	jmp	L_yakc_78
L_yakc_77:
	; >>>>> Line:	218
	; >>>>> tempDelay->prev->next = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	di, word [bp-2]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_78:
	; >>>>> Line:	220
	; >>>>> if(tempDelay->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_79
	; >>>>> Line:	221
	; >>>>> tempDelay->next- 
	mov	si, word [bp-2]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_79:
	; >>>>> Line:	224
	; >>>>> tempReady = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	225
	; >>>>> while(tempReady->priority < tempDelay->priority){ 
	jmp	L_yakc_81
L_yakc_80:
	; >>>>> Line:	226
	; >>>>> tempReady = tempReady->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_81:
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-2]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_80
L_yakc_82:
	; >>>>> Line:	228
	; >>>>> if(tempReady->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_83
	; >>>>> Line:	229
	; >>>>> YKRdyList = tempDelay; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_84
L_yakc_83:
	; >>>>> Line:	232
	; >>>>> tempReady->prev->next = tempDelay; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_84:
	; >>>>> Line:	235
	; >>>>> tempDelay->prev = tempReady->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	236
	; >>>>> tempDelay->next = tempReady; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	237
	; >>>>> tempReady->prev = tempDelay; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_76:
	; >>>>> Line:	239
	; >>>>> tempDelay = tempNext; 
	mov	ax, word [bp-6]
	mov	word [bp-2], ax
L_yakc_74:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_73
L_yakc_75:
	; >>>>> Line:	241
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_71:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_72
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	245
	; >>>>> YKSEM* YKSemCreate(int initialValue){ 
	jmp	L_yakc_86
L_yakc_87:
	; >>>>> Line:	247
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	248
	; >>>>> for (i = 0; YKSemArray[i].active; i++){}; 
	mov	word [bp-2], 0
	jmp	L_yakc_89
L_yakc_88:
L_yakc_91:
	; >>>>> Line:	248
	; >>>>> for (i = 0; YKSemArray[i].active; i++){}; 
	inc	word [bp-2]
L_yakc_89:
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_88
L_yakc_90:
	; >>>>> Line:	250
	; >>>>> YKSemArray[i].active = 1; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	; >>>>> Line:	251
	; >>>>> YKSemArray[i].val = initialValue; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	si, ax
	add	si, YKSemArray
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	252
	; >>>>> YKSemArray[i].id = i; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	254
	; >>>>> return &(YKSemArray[i]); 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
L_yakc_92:
	mov	sp, bp
	pop	bp
	ret
L_yakc_86:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_87
	ALIGN	2
YKSemPend:
	; >>>>> Line:	257
	; >>>>> void YKSemPend(YKSEM *semaphore){ 
	jmp	L_yakc_94
L_yakc_95:
	; >>>>> Line:	260
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	261
	; >>>>> semaphore->val = semaphore->val - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	mov	word [si], ax
	; >>>>> Line:	262
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	264
	; >>>>> if (semaphore->val >= 0){ return; } 
	mov	si, word [bp+4]
	cmp	word [si], 0
	jl	L_yakc_96
	; >>>>> Line:	264
	; >>>>> if (semaphore->val >= 0){ return; } 
	jmp	L_yakc_97
L_yakc_96:
	; >>>>> Line:	266
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	267
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	268
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	269
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	270
	; >>>>> readyTask->next = YKSemWaitList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKSemWaitList]
	mov	word [si], ax
	; >>>>> Line:	271
	; >>>>> YKSemWaitList = rea 
	mov	ax, word [bp-2]
	mov	word [YKSemWaitList], ax
	; >>>>> Line:	272
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	274
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_98
	; >>>>> Line:	275
	; >>>>> readyTask->next->prev = readyTask; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_98:
	; >>>>> Line:	278
	; >>>>> readyTask->semWait = semaphore; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	280
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	281
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_97:
	mov	sp, bp
	pop	bp
	ret
L_yakc_94:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_95
	ALIGN	2
YKSemPost:
	; >>>>> Line:	285
	; >>>>> void YKSemPost(YKSEM *semaphore){ 
	jmp	L_yakc_100
L_yakc_101:
	; >>>>> Line:	287
	; >>>>> unSuspTask = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	288
	; >>>>> semWaiting = YKSemWaitList; 
	mov	ax, word [YKSemWaitList]
	mov	word [bp-2], ax
	; >>>>> Line:	290
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	291
	; >>>>> semaphore->val = semaphore->val + 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	inc	ax
	mov	word [si], ax
	; >>>>> Line:	293
	; >>>>> while(semWaiting != 0){ 
	jmp	L_yakc_103
L_yakc_102:
	; >>>>> Line:	294
	; >>>>> if(semWaiting->semWait == semaphore){ 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_105
	; >>>>> Line:	295
	; >>>>> if((unSuspTask == 0) || (semWaiting->priority < unSuspTask->priority)){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_107
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_106
L_yakc_107:
	; >>>>> Line:	296
	; >>>>> unSuspTask = semWaiting; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
L_yakc_106:
L_yakc_105:
	; >>>>> Line:	299
	; >>>>> semWaiting = semWaiting->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_103:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_102
L_yakc_104:
	; >>>>> Line:	302
	; >>>>> if(unSuspTask == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_108
	; >>>>> Line:	303
	; >>>>> if(YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_109
	; >>>>> Line:	304
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_109:
	; >>>>> Line:	306
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	307
	; >>>>> return; 
	jmp	L_yakc_110
L_yakc_108:
	; >>>>> Line:	310
	; >>>>> if(unSuspTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_111
	; >>>>> Line:	311
	; >>>>> YKSemWaitList = unSuspTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKSemWaitList], ax
	jmp	L_yakc_112
L_yakc_111:
	; >>>>> Line:	314
	; >>>>> unSuspTask->prev->next = unSuspTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_112:
	; >>>>> Line:	317
	; >>>>> if (unSuspTask->next != 0){ 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_113
	; >>>>> Line:	318
	; >>>>> unSuspTask->next->prev = unSuspTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_113:
	; >>>>> Line:	322
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	323
	; >>>>> while (readyTask->priority < unSuspTask->priority){ 
	jmp	L_yakc_115
L_yakc_114:
	; >>>>> Line:	324
	; >>>>> queue->head = 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_115:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_114
L_yakc_116:
	; >>>>> Line:	326
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_117
	; >>>>> Line:	327
	; >>>>> YKRdyList = unSuspTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_118
L_yakc_117:
	; >>>>> Line:	330
	; >>>>> readyTask->prev->next = unSuspTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_118:
	; >>>>> Line:	332
	; >>>>> unSuspTask->prev = readyTask->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	333
	; >>>>> unSuspTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	334
	; >>>>> readyTask->prev = unSuspTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	336
	; >>>>> unSuspTask->semWait = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	338
	; >>>>> if( YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_119
	; >>>>> Line:	339
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_119:
	; >>>>> Line:	341
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_110:
	; >>>>> Line:	342
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_100:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_101
	ALIGN	2
queueInsert:
	; >>>>> Line:	345
	; >>>>> void queueInsert(YKQ* queue, void* msg){ 
	jmp	L_yakc_121
L_yakc_122:
	; >>>>> Line:	346
	; >>>>> queue->base_addr[queue->head] = msg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	347
	; >>>>> if(queue->head < queue->size){ 
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_123
	; >>>>> Line:	348
	; >>>>> queue->head += 1; 
	mov	si, word [bp+4]
	add	si, 6
	inc	word [si]
	jmp	L_yakc_124
L_yakc_123:
	; >>>>> Line:	351
	; >>>>> queue->head = 
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], 0
L_yakc_124:
	mov	sp, bp
	pop	bp
	ret
L_yakc_121:
	push	bp
	mov	bp, sp
	jmp	L_yakc_122
	ALIGN	2
queueRemove:
	; >>>>> Line:	355
	; >>>>> void* queueRemove(YKQ* queue){ 
	jmp	L_yakc_126
L_yakc_127:
	; >>>>> Line:	357
	; >>>>> msg = *(queue->base_addr + queue->tail); 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	358
	; >>>>> if(queue->tail > 0){ 
	mov	si, word [bp+4]
	add	si, 8
	cmp	word [si], 0
	jle	L_yakc_128
	; >>>>> Line:	359
	; >>>>> queue->head -= 1; 
	mov	si, word [bp+4]
	add	si, 6
	dec	word [si]
	jmp	L_yakc_129
L_yakc_128:
	; >>>>> Line:	362
	; >>>>> queue->head = queue->size - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	add	si, 6
	mov	word [si], ax
L_yakc_129:
	; >>>>> Line:	364
	; >>>>> return msg; 
	mov	ax, word [bp-2]
L_yakc_130:
	mov	sp, bp
	pop	bp
	ret
L_yakc_126:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_127
	ALIGN	2
YKQCreate:
	; >>>>> Line:	367
	; >>>>> YKQ *YKQCreate(void **start, unsigned size){ 
	jmp	L_yakc_132
L_yakc_133:
	; >>>>> Line:	369
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	370
	; >>>>> for (i = 0; YKQueueArray[i].base_addr; i++){}; 
	mov	word [bp-2], 0
	jmp	L_yakc_135
L_yakc_134:
L_yakc_137:
	; >>>>> Line:	370
	; >>>>> for (i = 0; YKQueueArray[i].base_addr; i++){}; 
	inc	word [bp-2]
L_yakc_135:
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_134
L_yakc_136:
	; >>>>> Line:	372
	; >>>>> YKQueueArray[i].base_addr = start; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	373
	; >>>>> YKQueueArray[i].cur_length = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	374
	; >>>>> YKQueueArray[i].size = size; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	mov	si, ax
	add	si, YKQueueArray
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	375
	; >>>>> YKQueueArray[i].tail = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	376
	; >>>>> YKQueueArray[i].head = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	377
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	378
	; >>>>> ur_le 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
L_yakc_138:
	mov	sp, bp
	pop	bp
	ret
L_yakc_132:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_133
	ALIGN	2
YKQPend:
	; >>>>> Line:	382
	; >>>>> void *YKQPend(YKQ *queue){ 
	jmp	L_yakc_140
L_yakc_141:
	; >>>>> Line:	385
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	386
	; >>>>> if(queue->cur_length == 0){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_142
	; >>>>> Line:	387
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	388
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	389
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	390
	; >>>>> readyTask->next = YKQWaitList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKQWaitList]
	mov	word [si], ax
	; >>>>> Line:	391
	; >>>>> YKQWaitList = readyTask; 
	mov	ax, word [bp-2]
	mov	word [YKQWaitList], ax
	; >>>>> Line:	392
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	394
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_143
	; >>>>> Line:	395
	; >>>>> readyTask->next->prev = readyTask; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_143:
	; >>>>> Line:	398
	; >>>>> readyTask->queueWait = queue; 
	mov	si, word [bp-2]
	add	si, 14
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	399
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_142:
	; >>>>> Line:	401
	; >>>>> msg = *(queue->base_addr + queue->tail); 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	402
	; >>>>> queue->cur_le 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	dec	ax
	mov	si, word [bp+4]
	add	si, 2
	mov	word [si], ax
	; >>>>> Line:	404
	; >>>>> if((queue->tail + 1) < queue->size){ 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	mov	dx, word [si]
	cmp	dx, ax
	jle	L_yakc_144
	; >>>>> Line:	405
	; >>>>> queue->tail = queue->tail + 1; 
	add	si, 8
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], ax
	jmp	L_yakc_145
L_yakc_144:
	; >>>>> Line:	408
	; >>>>> queue->tail = 0; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 0
L_yakc_145:
	; >>>>> Line:	411
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	412
	; >>>>> return msg; 
	mov	ax, word [bp-4]
L_yakc_146:
	mov	sp, bp
	pop	bp
	ret
L_yakc_140:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_141
	ALIGN	2
YKQPost:
	; >>>>> Line:	415
	; >>>>> int YKQPost(YKQ *queue, void *msg){ 
	jmp	L_yakc_148
L_yakc_149:
	; >>>>> Line:	417
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	419
	; >>>>> if((queue->cur_length) == (queue->size-1)){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	di, word [bp+4]
	mov	ax, word [di]
	dec	ax
	cmp	ax, word [si]
	jne	L_yakc_150
	; >>>>> Line:	420
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_yakc_151
L_yakc_150:
	; >>>>> Line:	422
	; >>>>> unWaitTask = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	423
	; >>>>> queueWait = YKQWaitList; 
	mov	ax, word [YKQWaitList]
	mov	word [bp-2], ax
	; >>>>> Line:	425
	; >>>>> *(queue->base_addr + queue->head) = msg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	426
	; >>>>> queue->cur_length = queue->cur_length + 1; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 2
	mov	word [si], ax
	; >>>>> Line:	427
	; >>>>> if((queue->head + 1) < queue->size){ 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	mov	dx, word [si]
	cmp	dx, ax
	jle	L_yakc_152
	; >>>>> Line:	428
	; >>>>> queue->head = queue->head + 1; 
	add	si, 6
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], ax
	jmp	L_yakc_153
L_yakc_152:
	; >>>>> Line:	431
	; >>>>> queue->head = 0; 
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], 0
L_yakc_153:
	; >>>>> Line:	434
	; >>>>> while(queueWait != 0){ 
	jmp	L_yakc_155
L_yakc_154:
	; >>>>> Line:	435
	; >>>>> if(queueWait->queueWait == queue){ 
	mov	si, word [bp-2]
	add	si, 14
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_157
	; >>>>> Line:	436
	; >>>>> if((unWaitTask == 0) || (queueWait->priority < unWaitTask->priority)){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_159
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_158
L_yakc_159:
	; >>>>> Line:	437
	; >>>>> unWaitTask = queueWait; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
L_yakc_158:
L_yakc_157:
	; >>>>> Line:	440
	; >>>>> queueWait = queueWait->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_155:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_154
L_yakc_156:
	; >>>>> Line:	443
	; >>>>> if(unWaitTask == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_160
	; >>>>> Line:	444
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	445
	; >>>>> return 1; 
	mov	ax, 1
	jmp	L_yakc_151
L_yakc_160:
	; >>>>> Line:	448
	; >>>>> if(unWaitTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_161
	; >>>>> Line:	449
	; >>>>> YKQWaitList = unWaitTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKQWaitList], ax
	jmp	L_yakc_162
L_yakc_161:
	; >>>>> Line:	452
	; >>>>> unWaitTask->prev->next = unWaitTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_162:
	; >>>>> Line:	455
	; >>>>> if (unWaitTask->next ! 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_163
	; >>>>> Line:	456
	; >>>>> unWaitTask->next->prev = unWaitTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_163:
	; >>>>> Line:	459
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	460
	; >>>>> while (readyTask->priority < unWaitTask->priority){ 
	jmp	L_yakc_165
L_yakc_164:
	; >>>>> Line:	461
	; >>>>> readyTask = readyTask->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_165:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_164
L_yakc_166:
	; >>>>> Line:	463
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_167
	; >>>>> Line:	464
	; >>>>> YKRdyList = unWaitTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_168
L_yakc_167:
	; >>>>> Line:	467
	; >>>>> readyTask->prev->next = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_168:
	; >>>>> Line:	469
	; >>>>> unWaitTask->prev = readyTask->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	470
	; >>>>> unWaitTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	471
	; >>>>> readyTask->prev = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	473
	; >>>>> unWaitTask->queueWait = 0; 
	mov	si, word [bp-4]
	add	si, 14
	mov	word [si], 0
	; >>>>> Line:	475
	; >>>>> if(YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_169
	; >>>>> Line:	476
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_169:
	; >>>>> Line:	478
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	479
	; >>>>> return 1; 
	mov	ax, 1
L_yakc_151:
	mov	sp, bp
	pop	bp
	ret
L_yakc_148:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_149
	ALIGN	2
YKEventCreate:
	; >>>>> Line:	484
	; >>>>> ; 
	jmp	L_yakc_171
L_yakc_172:
	; >>>>> Line:	486
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	487
	; >>>>> for (i = 0; YKEVENTArray[i].active; i++){}; 
	mov	word [bp-2], 0
	jmp	L_yakc_174
L_yakc_173:
L_yakc_176:
	; >>>>> Line:	487
	; >>>>> for (i = 0; YKEVENTArray[i].active; i++){}; 
	inc	word [bp-2]
L_yakc_174:
	mov	ax, word [bp-2]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, YKEVENTArray
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_173
L_yakc_175:
	; >>>>> Line:	489
	; >>>>> YKEVENTArray[i].active = 1; 
	mov	ax, word [bp-2]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, YKEVENTArray
	mov	word [si], 1
	; >>>>> Line:	490
	; >>>>> YKEVENTArray[i].flag = initialValue; 
	mov	ax, word [bp-2]
	shl	ax, 1
	shl	ax, 1
	add	ax, YKEVENTArray
	mov	si, ax
	add	si, 2
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	492
	; >>>>> return &(YKEVENTArray[i]); 
	mov	ax, word [bp-2]
	shl	ax, 1
	shl	ax, 1
	add	ax, YKEVENTArray
L_yakc_177:
	mov	sp, bp
	pop	bp
	ret
L_yakc_171:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_172
	ALIGN	2
YKEventPend:
	; >>>>> Line:	495
	; >>>>> unsigned YKEventPend(YKEVENT *event, unsigned eventMask, int waitMode){ 
	jmp	L_yakc_179
L_yakc_180:
	; >>>>> Line:	498
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	500
	; >>>>> if(((waitMode == 0) && ((eventMask & event->flag ) > 0 )) || 
	mov	ax, word [bp+8]
	test	ax, ax
	jne	L_yakc_183
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	and	ax, word [bp+6]
	jne	L_yakc_182
L_yakc_183:
	cmp	word [bp+8], 1
	jne	L_yakc_181
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	and	ax, word [bp+6]
	mov	dx, word [bp+6]
	cmp	dx, ax
	jne	L_yakc_181
L_yakc_182:
	; >>>>> Line:	502
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	503
	; >>>>> return event->flag; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	jmp	L_yakc_184
L_yakc_181:
	; >>>>> Line:	506
	; >>>>> ext; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	507
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	508
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	509
	; >>>>> readyTask->next = YKEventWaitList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKEventWaitList]
	mov	word [si], ax
	; >>>>> Line:	510
	; >>>>> YKEventWaitList = readyTask; 
	mov	ax, word [bp-2]
	mov	word [YKEventWaitList], ax
	; >>>>> Line:	511
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	513
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_185
	; >>>>> Line:	514
	; >>>>> readyTask->next->prev = readyTask; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_185:
	; >>>>> Line:	517
	; >>>>> readyTask->event = event; 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	518
	; >>>>> readyTask->eventMask = eventMask; 
	mov	si, word [bp-2]
	add	si, 18
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	519
	; >>>>> readyTask->waitMode = waitMode; 
	mov	si, word [bp-2]
	add	si, 20
	mov	ax, word [bp+8]
	mov	word [si], ax
	; >>>>> Line:	521
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	522
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	524
	; >>>>> return event->flag; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
L_yakc_184:
	mov	sp, bp
	pop	bp
	ret
L_yakc_179:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_180
	ALIGN	2
YKEventSet:
	; >>>>> Line:	527
	; >>>>> void YKEventSet(YKEVENT *event, unsigned eventMask){ 
	jmp	L_yakc_187
L_yakc_188:
	; >>>>> Line:	529
	; >>>>> s 
	call	YKEnterMutex
	; >>>>> Line:	530
	; >>>>> event->flag |= eventMask; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [bp+6]
	or	word [si], ax
	; >>>>> Line:	532
	; >>>>> for(eventTask = YKEventWaitList; eventTask != 0; ){ 
	mov	ax, word [YKEventWaitList]
	mov	word [bp-2], ax
	jmp	L_yakc_190
L_yakc_189:
	; >>>>> Line:	533
	; >>>>> taskNext=eventTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-8], ax
	; >>>>> Line:	534
	; >>>>> if(eventTask->event != event){ 
	mov	si, word [bp-2]
	add	si, 16
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	je	L_yakc_193
	; >>>>> Line:	535
	; >>>>> eventTask = taskNext; 
	mov	ax, word [bp-8]
	mov	word [bp-2], ax
	; >>>>> Line:	536
	; >>>>> continue; 
	jmp	L_yakc_192
	jmp	L_yakc_194
L_yakc_193:
	; >>>>> Line:	539
	; >>>>> if( ((eventTask->waitMode == 0) && ((eventTask->eventMask & event->flag ) > 0 )) || 
	mov	si, word [bp-2]
	add	si, 20
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_197
	mov	si, word [bp-2]
	add	si, 18
	mov	ax, word [si]
	mov	si, word [bp+4]
	add	si, 2
	and	ax, word [si]
	jne	L_yakc_196
L_yakc_197:
	mov	si, word [bp-2]
	add	si, 20
	cmp	word [si], 1
	jne	L_yakc_195
	mov	si, word [bp-2]
	add	si, 18
	mov	ax, word [si]
	mov	si, word [bp+4]
	add	si, 2
	and	ax, word [si]
	mov	si, word [bp-2]
	add	si, 18
	mov	dx, word [si]
	cmp	dx, ax
	jne	L_yakc_195
L_yakc_196:
	; >>>>> Line:	541
	; >>>>> unWaitTask = eventTask; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
	; >>>>> Line:	543
	; >>>>> if(unWaitTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_198
	; >>>>> Line:	544
	; >>>>> WaitTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKEventWaitList], ax
	jmp	L_yakc_199
L_yakc_198:
	; >>>>> Line:	547
	; >>>>> unWaitTask->prev->next = unWaitTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_199:
	; >>>>> Line:	549
	; >>>>> if (unWaitTask->next != 0){ 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_200
	; >>>>> Line:	550
	; >>>>> unWaitTask->next->prev = unWaitTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_200:
	; >>>>> Line:	552
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	553
	; >>>>> while (readyTask->priority < unWaitTask->priority){ 
	jmp	L_yakc_202
L_yakc_201:
	; >>>>> Line:	554
	; >>>>> readyTask = readyTask->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_202:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_201
L_yakc_203:
	; >>>>> Line:	556
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_204
	; >>>>> Line:	557
	; >>>>> YKRdyList = unWaitTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_205
L_yakc_204:
	; >>>>> Line:	560
	; >>>>> readyTask->prev->next = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_205:
	; >>>>> Line:	562
	; >>>>> unWaitTa 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	563
	; >>>>> unWaitTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	564
	; >>>>> readyTask->prev = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	566
	; >>>>> unWaitTask->event = 0; 
	mov	si, word [bp-4]
	add	si, 16
	mov	word [si], 0
	jmp	L_yakc_206
L_yakc_195:
	; >>>>> Line:	569
	; >>>>> unWaitTask = 0; 
	mov	word [bp-4], 0
L_yakc_206:
L_yakc_194:
	; >>>>> Line:	572
	; >>>>> eventTask = taskNext; 
	mov	ax, word [bp-8]
	mov	word [bp-2], ax
L_yakc_192:
L_yakc_190:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_189
L_yakc_191:
	; >>>>> Line:	574
	; >>>>> if(YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_207
	; >>>>> Line:	575
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_207:
	; >>>>> Line:	577
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_187:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_yakc_188
	ALIGN	2
YKEventReset:
	; >>>>> Line:	580
	; >>>>> void YKEventReset(YKEVENT *event, unsigned eventMask){ 
	jmp	L_yakc_209
L_yakc_210:
	; >>>>> Line:	581
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	582
	; >>>>> event->flag &= ~eventMask; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [bp+6]
	not	ax
	and	word [si], ax
	; >>>>> Line:	583
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_209:
	push	bp
	mov	bp, sp
	jmp	L_yakc_210
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKDelayList:
	TIMES	2 db 0
YKSemWaitList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	220 db 0
idleStack:
	TIMES	512 db 0
YKISRDepth:
	TIMES	2 db 0
YKSemArray:
	TIMES	60 db 0
YKQueueArray:
	TIMES	50 db 0
YKEVENTArray:
	TIMES	20 db 0
YKQWaitList:
	TIMES	2 db 0
YKEventWaitList:
	TIMES	2 db 0
TKCurrentlyRunning:
	TIMES	2 db 0
;Assemble funtcions

YKEnterMutex:                   ; Disables interrupts
	cli	                          ; clear interrupt flag
	ret


YKExitMutex:                    ; Enables Interrupts
	sti	                          ; set interrupt flag
	ret

YKDispatcherNSave:   		; Dispatcher that saves to mem/stack

  cli

	push bp			; Push the base pointer onto the stack
	mov bp, sp		; set the current base pointer to be the stack pointer

	; Get the sp values to restore and save them to sp
	mov sp, word[bp+4]			; getting first arg (highest priority task sp)

	;mov	al, 0x20
	;out 	0x20, al

	; Pop register values off the stack
	pop ES
	pop DS
	pop DI
	pop SI
	pop BP
	pop DX
	pop CX
	pop BX
	pop AX

	iret

YKDispatcherSave:   		; Dispatcher that saves to mem/stack

  cli

	push bp
	mov bp, sp

	mov AX, [bp+2]

	pop bp
	add sp, 2

	; Push flags, CS, and IP to the stack
	pushf

	; This is something about the flags that Ian told me to do
	;push BX
	;add sp, 2
	;pop BX
	;or BX, 0x200
	;push BX
	;sub sp, 2
	;pop BX

	push CS
	push AX
	;push word[bp+2]

	; Push all register values to the stack
	push AX
	push BX
	push CX
	push DX
	push BP
	push SI
	push DI
	push DS
	push ES

	; Move bp back to its original value
	mov bp, sp
	add bp, 20

	; Store the save sp to si
	mov si, word [bp+4] 			; getting first arg (sp)
	mov word [si], sp

restore_context:

	; Save the sp and ss values to restore to sp and ss
	mov sp, word[bp+6]			; getting second arg

	;mov	al, 0x20
	;out 	0x20, al

	; Pop register values back off the stack
	pop ES
	pop DS
	pop DI
	pop SI
	pop BP
	pop DX
	pop CX
	pop BX
	pop AX
	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab8app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
corner_flag:
	DW	0
	ALIGN	2
getIndex:
	jmp	L_lab8app_1
L_lab8app_2:
	cmp	word [moveQueueIndex], 50
	jne	L_lab8app_3
	mov	word [moveQueueIndex], 0
L_lab8app_3:
	mov	ax, word [moveQueueIndex]
	inc	word [moveQueueIndex]
L_lab8app_4:
	mov	sp, bp
	pop	bp
	ret
L_lab8app_1:
	push	bp
	mov	bp, sp
	jmp	L_lab8app_2
	ALIGN	2
L_lab8app_6:
	DW	0
L_lab8app_8:
	DB	" ",0xD,0xA,0
L_lab8app_7:
	DB	" Corner Ori: ",0
	ALIGN	2
newPieceTask:
	jmp	L_lab8app_9
L_lab8app_10:
	mov	word [bp-2], 0
	jmp	L_lab8app_12
L_lab8app_11:
	push	word [newPieceQueue]
	call	YKQPend
	add	sp, 2
	mov	word [bp-6], ax
	mov	si, word [bp-6]
	add	si, 2
	cmp	word [si], 1
	jne	L_lab8app_14
	mov	si, word [bp-6]
	add	si, 6
	mov	ax, word [si]
	mov	word [bp-4], ax
	cmp	word [bp-4], 5
	jne	L_lab8app_15
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
	jmp	L_lab8app_16
L_lab8app_15:
	jmp	L_lab8app_18
L_lab8app_17:
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	inc	word [bp-4]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_18:
	cmp	word [bp-4], 4
	jl	L_lab8app_17
L_lab8app_19:
L_lab8app_16:
	mov	si, word [bp-6]
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	je	L_lab8app_20
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_20:
	jmp	L_lab8app_21
L_lab8app_14:
	mov	si, word [bp-6]
	add	si, 6
	mov	ax, word [si]
	mov	word [bp-4], ax
	cmp	word [bp-4], 5
	jne	L_lab8app_22
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	dec	word [bp-4]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
	jmp	L_lab8app_23
L_lab8app_22:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_lab8app_24
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	inc	word [bp-4]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_24:
L_lab8app_23:
	mov	ax, word [L_lab8app_6]
	test	ax, ax
	jne	L_lab8app_25
	mov	word [L_lab8app_6], 1
	mov	si, word [bp-6]
	add	si, 4
	cmp	word [si], 1
	jne	L_lab8app_26
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_26:
	mov	si, word [bp-6]
	add	si, 4
	cmp	word [si], 3
	jne	L_lab8app_27
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_27:
	mov	si, word [bp-6]
	add	si, 4
	cmp	word [si], 2
	jne	L_lab8app_28
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_28:
	jmp	L_lab8app_30
L_lab8app_29:
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	dec	word [bp-4]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_30:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_lab8app_29
L_lab8app_31:
	jmp	L_lab8app_32
L_lab8app_25:
	mov	word [L_lab8app_6], 0
	mov	si, word [bp-6]
	add	si, 4
	cmp	word [si], 1
	jne	L_lab8app_33
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_33:
	mov	si, word [bp-6]
	add	si, 4
	cmp	word [si], 3
	jne	L_lab8app_34
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_34:
	mov	si, word [bp-6]
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	jne	L_lab8app_35
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], RotatePiece
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_35:
	cmp	word [bp-4], 2
	jle	L_lab8app_36
	jmp	L_lab8app_38
L_lab8app_37:
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	dec	word [bp-4]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_38:
	cmp	word [bp-4], 2
	jne	L_lab8app_37
L_lab8app_39:
	jmp	L_lab8app_40
L_lab8app_36:
	cmp	word [bp-4], 2
	jge	L_lab8app_41
	jmp	L_lab8app_43
L_lab8app_42:
	call	getIndex
	mov	word [bp-2], ax
	mov	si, word [bp-6]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	di, ax
	add	di, movePieceList
	mov	ax, word [si]
	mov	word [di], ax
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	mov	si, ax
	add	si, 4
	mov	word [si], SlidePiece
	inc	word [bp-4]
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, movePieceList
	push	ax
	push	word [movePieceQueue]
	call	YKQPost
	add	sp, 4
L_lab8app_43:
	cmp	word [bp-4], 2
	jne	L_lab8app_42
L_lab8app_44:
L_lab8app_41:
L_lab8app_40:
L_lab8app_32:
	mov	ax, L_lab8app_7
	push	ax
	call	printString
	add	sp, 2
	push	word [bp-4]
	call	printInt
	add	sp, 2
	mov	ax, L_lab8app_8
	push	ax
	call	printString
	add	sp, 2
L_lab8app_21:
L_lab8app_12:
	jmp	L_lab8app_11
L_lab8app_13:
	mov	sp, bp
	pop	bp
	ret
L_lab8app_9:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_lab8app_10
	ALIGN	2
movePieceTask:
	jmp	L_lab8app_46
L_lab8app_47:
	jmp	L_lab8app_49
L_lab8app_48:
	push	word [movePieceSem]
	call	YKSemPend
	add	sp, 2
	push	word [movePieceQueue]
	call	YKQPend
	add	sp, 2
	mov	word [bp-2], ax
	mov	si, word [bp-2]
	add	si, 2
	push	word [si]
	mov	si, word [bp-2]
	push	word [si]
	add	si, 4
	mov	si, word [si]
	call	si
	add	sp, 4
L_lab8app_49:
	jmp	L_lab8app_48
L_lab8app_50:
	mov	sp, bp
	pop	bp
	ret
L_lab8app_46:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_lab8app_47
L_lab8app_56:
	DB	"% >>>>>",0xD,0xA,0
L_lab8app_55:
	DB	", CPU usage: ",0
L_lab8app_54:
	DB	"<<<<< Context switches: ",0
L_lab8app_53:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab8app_52:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
STask:
	jmp	L_lab8app_57
L_lab8app_58:
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	mov	ax, L_lab8app_52
	push	ax
	call	printString
	add	sp, 2
	mov	ax, L_lab8app_53
	push	ax
	call	printString
	add	sp, 2
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	mov	word [YKIdleCount], 0
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	mov	ax, word [YKIdleCount]
	xor	dx, dx
	mov	cx, 25
	div	cx
	mov	word [bp-2], ax
	mov	word [YKIdleCount], 0
	mov	ax, 836
	xor	dx, dx
	push	dx
	push	ax
	call	SeedSimptris
	add	sp, 4
	mov	al, 3
	push	ax
	mov	ax, (newPieceTaskStk+1024)
	push	ax
	mov	ax, newPieceTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	al, 5
	push	ax
	mov	ax, (movePieceTaskStk+1024)
	push	ax
	mov	ax, movePieceTask
	push	ax
	call	YKNewTask
	add	sp, 6
	call	StartSimptris
	jmp	L_lab8app_60
L_lab8app_59:
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	call	YKEnterMutex
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	mov	ax, word [YKIdleCount]
	mov	word [bp-6], ax
	call	YKExitMutex
	mov	ax, L_lab8app_54
	push	ax
	call	printString
	add	sp, 2
	push	word [bp-4]
	call	printInt
	add	sp, 2
	mov	ax, L_lab8app_55
	push	ax
	call	printString
	add	sp, 2
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	mov	ax, L_lab8app_56
	push	ax
	call	printString
	add	sp, 2
	call	YKEnterMutex
	mov	word [YKCtxSwCount], 0
	mov	word [YKIdleCount], 0
	call	YKExitMutex
L_lab8app_60:
	jmp	L_lab8app_59
L_lab8app_61:
	mov	sp, bp
	pop	bp
	ret
L_lab8app_57:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab8app_58
	ALIGN	2
main:
	jmp	L_lab8app_63
L_lab8app_64:
	call	YKInitialize
	mov	ax, 50
	push	ax
	mov	ax, newPieceQue
	push	ax
	call	YKQCreate
	add	sp, 4
	mov	word [newPieceQueue], ax
	mov	ax, 50
	push	ax
	mov	ax, movePieceQue
	push	ax
	call	YKQCreate
	add	sp, 4
	mov	word [movePieceQueue], ax
	mov	ax, 1
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [movePieceSem], ax
	mov	ax, (L_lab8app_7+12)
	push	ax
	call	printString
	add	sp, 2
	xor	al, al
	push	ax
	mov	ax, (STaskStk+1024)
	push	ax
	mov	ax, STask
	push	ax
	call	YKNewTask
	add	sp, 6
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab8app_63:
	push	bp
	mov	bp, sp
	jmp	L_lab8app_64
	ALIGN	2
movePieceQueue:
	TIMES	2 db 0
newPieceQueue:
	TIMES	2 db 0
movePieceSem:
	TIMES	2 db 0
newPieceTaskStk:
	TIMES	1024 db 0
movePieceTaskStk:
	TIMES	1024 db 0
STaskStk:
	TIMES	1024 db 0
moveQueueIndex:
	TIMES	2 db 0
movePieceList:
	TIMES	300 db 0
newPieceList:
	TIMES	400 db 0
newPieceQue:
	TIMES	100 db 0
movePieceQue:
	TIMES	100 db 0
