; Generated by c86 (BYU-NASM) 5.1 (beta) from lab8_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
clearLine:
	; >>>>> Line:	8
	; >>>>> void clearLine(){ 
	jmp	L_lab8_app_1
L_lab8_app_2:
	; >>>>> Line:	10
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_lab8_app_1:
	push	bp
	mov	bp, sp
	jmp	L_lab8_app_2
	ALIGN	2
printScreen:
	; >>>>> Line:	12
	; >>>>> void printScreen(void){ 
	jmp	L_lab8_app_4
L_lab8_app_5:
	; >>>>> Line:	14
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_lab8_app_4:
	push	bp
	mov	bp, sp
	jmp	L_lab8_app_5
	ALIGN	2
newPieceTask:
	; >>>>> Line:	16
	; >>>>> int newPieceTask(void){ 
	jmp	L_lab8_app_7
L_lab8_app_8:
	; >>>>> Line:	18
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_lab8_app_7:
	push	bp
	mov	bp, sp
	jmp	L_lab8_app_8
	ALIGN	2
movePieceTask:
	; >>>>> Line:	20
	; >>>>> int movePieceTask(void){ 
	jmp	L_lab8_app_10
L_lab8_app_11:
	; >>>>> Line:	22
	; >>>>> } 
	mov	sp, bp
	pop	bp
	ret
L_lab8_app_10:
	push	bp
	mov	bp, sp
	jmp	L_lab8_app_11
