        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      RESET ; Reset               ; Int 08h (IRQ 0)
        dd      TICK ; Tick                ; Int 09h (IRQ 1)
        dd      KEY ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84
; ISR file
;1 Save the context of whatever was running by pushing all registers onto the stack, except SP, SS, CS, IP, and the flags.
;2 Enable interrupts to allow higher priority IRQs to interrupt.
;3 Run the interrupt handler, which is usually a C function that does the work for this interrupt.
;4 Disable interrupts.
;5 Send the EOI command to the PIC, informing it that the handler is finished.
;6 Restore the context of what was running before the interrupt occurred by popping the registers saved in step 1 off the stack.
;7 Execute the iret instruction. This restores in one atomic operation the values for IP, CS, and the flags, which were automatically -
;	; - saved on the stack by the processor when the interrupt occurred. This effectively restores execution to the point where the interrupt occurred.

RESET:
	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

	call YKEnterISR

	sti
	call c_reset_handler
	cli

	mov al, 0x20        ; send eoi to pic
	out 0x20, al        ; send eoi to pic

	call YKExitISR

	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret


KEY:

	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

  mov ax, [YKISRDepth]          ;save the depth counter
	cmp ax, 0                     ; check if the depth is zero, if it is save the SP of the task we are interupting
	jnz key_not_lowest_interrupt  ; skip saving the stack because we are not interupting that task

	mov bx, [YKRdyList] ; save the sp
	mov [bx], sp

key_not_lowest_interrupt:
	call YKEnterISR

	sti                 ; enable interrupts for higher priority IRQs ?
	call c_key_handler  ; run
	cli                 ; disable interrupts ?

	mov al, 0x20        ; send eoi to pic
	out 0x20, al        ; send eoi to pic

	call YKExitISR

	;restore reg
	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret

TICK:
	; save reg
	push ax
	push bx
	push cx
	push dx
	push bp
	push si
	push di
	push ds
	push es

  mov ax, [YKISRDepth] ;save the depth counter
	cmp ax, 0            ; check if the depth is zero, if it is save the SP of the task we are interupting
	jnz not_lowest_interrupt


	mov bx, [YKRdyList] ; save SP of interupted task
	mov [bx], sp

not_lowest_interrupt:
	call YKEnterISR

	sti                 ; enable interrupts for higher priority IRQs ?

	;call YKTickHandler;
	call c_tick_handler ; run interrupt handler ? I think this is the c file

	cli                 ; disable interrupts

	mov al, 0x20        ; send eoi to pic
	out 0x20, al        ; send eoi to pic

	call YKExitISR

	;restore
	pop es
	pop ds
	pop di
	pop si
	pop bp
	pop dx
	pop cx
	pop bx
	pop ax

	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
c_reset_handler:
	; >>>>> Line:	16
	; >>>>> void c_reset_handler(){ 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	17
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
	ALIGN	2
L_myinth_4:
	DW	0
L_myinth_5:
	DW	0
L_myinth_6:
	DB	"  TickISR: queue overflow! ",0xA,0
	ALIGN	2
c_tick_handler:
	; >>>>> Line:	20
	; >>>>> void c_tick_handler(){ 
	jmp	L_myinth_7
L_myinth_8:
	; >>>>> Line:	23
	; >>>>> YKTickHandler(); 
	call	YKTickHandler
	; >>>>> Line:	26
	; >>>>> MsgArray[next].tick = YKTickNum; 
	mov	ax, word [L_myinth_4]
	shl	ax, 1
	shl	ax, 1
	mov	si, ax
	add	si, MsgArray
	mov	ax, word [YKTickNum]
	mov	word [si], ax
	; >>>>> Line:	27
	; >>>>> data = (data + 89) % 100; 
	mov	ax, word [L_myinth_5]
	add	ax, 89
	cwd
	mov	cx, 100
	idiv	cx
	mov	ax, dx
	mov	word [L_myinth_5], ax
	; >>>>> Line:	28
	; >>>>> MsgArray[next].data = data; 
	mov	ax, word [L_myinth_4]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	mov	si, ax
	add	si, 2
	mov	ax, word [L_myinth_5]
	mov	word [si], ax
	; >>>>> Line:	30
	; >>>>> if (YKQPost(MsgQPtr, (void *) &(MsgArray[next])) == 0){ 
	mov	ax, word [L_myinth_4]
	shl	ax, 1
	shl	ax, 1
	add	ax, MsgArray
	push	ax
	push	word [MsgQPtr]
	call	YKQPost
	add	sp, 4
	test	ax, ax
	jne	L_myinth_9
	; >>>>> Line:	31
	; >>>>> printString("  TickISR: queue overflow! \n"); 
	mov	ax, L_myinth_6
	push	ax
	call	printString
	add	sp, 2
	jmp	L_myinth_10
L_myinth_9:
	; >>>>> Line:	33
	; >>>>> else if (++next >= 20){ 
	mov	ax, word [L_myinth_4]
	inc	ax
	mov	word [L_myinth_4], ax
	cmp	ax, 20
	jl	L_myinth_11
	; >>>>> Line:	34
	; >>>>> next = 0; 
	mov	word [L_myinth_4], 0
L_myinth_11:
L_myinth_10:
	mov	sp, bp
	pop	bp
	ret
L_myinth_7:
	push	bp
	mov	bp, sp
	jmp	L_myinth_8
	ALIGN	2
c_key_handler:
	; >>>>> Line:	44
	; >>>>> void c_key_handler(){ 
	jmp	L_myinth_13
L_myinth_14:
	; >>>>> Line:	45
	; >>>>> GlobalFlag = 1; 
	mov	word [GlobalFlag], 1
	mov	sp, bp
	pop	bp
	ret
L_myinth_13:
	push	bp
	mov	bp, sp
	jmp	L_myinth_14
; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
tickcount:
	DW	0
run_flag:
	DB	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	30
	; >>>>> void YKInitialize(void){ 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	32
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	33
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	34
	; >>>>> TKCurrentlyRunning = 0; 
	mov	word [TKCurrentlyRunning], 0
	; >>>>> Line:	35
	; >>>>> YKISRDepth = 0; 
	mov	word [YKISRDepth], 0
	; >>>>> Line:	37
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	39
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	42
	; >>>>> YKAvailTCBList = &(YKTCBArray[0]); 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	44
	; >>>>> for (i = 0; i < 9; i++) 
	mov	word [bp-2], 0
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	45
	; >>>>> YKTCBArray[i].next = &(YKTCBArray[i+1]); 
	mov	ax, word [bp-2]
	inc	ax
	mov	cx, 4
	shl	ax, cl
	add	ax, YKTCBArray
	mov	dx, word [bp-2]
	mov	cx, 4
	shl	dx, cl
	add	dx, YKTCBArray
	mov	si, dx
	add	si, 8
	mov	word [si], ax
L_yakc_6:
	inc	word [bp-2]
L_yakc_4:
	cmp	word [bp-2], 9
	jl	L_yakc_3
L_yakc_5:
	; >>>>> Line:	46
	; >>>>> YKTCBArray[9].next = 0; 
	mov	word [(152+YKTCBArray)], 0
	; >>>>> Line:	48
	; >>>>> for (i = 0; i < 19; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_8
L_yakc_7:
	; >>>>> Line:	49
	; >>>>> priori 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	si, ax
	add	si, YKSemArray
	mov	word [si], -10
	; >>>>> Line:	50
	; >>>>> YKSemArray[i].active = 0; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	51
	; >>>>> YKSemArray[i].id = i; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_10:
	inc	word [bp-2]
L_yakc_8:
	cmp	word [bp-2], 19
	jl	L_yakc_7
L_yakc_9:
	; >>>>> Line:	54
	; >>>>> for (i = 0; i < 2; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_12
L_yakc_11:
	; >>>>> Line:	55
	; >>>>> YKQueueArray[i].size = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	mov	si, ax
	add	si, YKQueueArray
	mov	word [si], 0
	; >>>>> Line:	56
	; >>>>> YKQueueArray[i].length = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	57
	; >>>>> YKQueueArray[i].base_addr = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	58
	; >>>>> YKQueueArray[i].head = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	59
	; >>>>> YKQueueArray[i].tail = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 8
	mov	word [si], 0
L_yakc_14:
	inc	word [bp-2]
L_yakc_12:
	cmp	word [bp-2], 2
	jl	L_yakc_11
L_yakc_13:
	; >>>>> Line:	63
	; >>>>> YKNewTask(YKIdleTask, (void*)&idleStack[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (idleStack+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	66
	; >>>>> void YKIdleTask(void){ 
	jmp	L_yakc_16
L_yakc_17:
	; >>>>> Line:	67
	; >>>>> while(1){ 
	jmp	L_yakc_19
L_yakc_18:
	; >>>>> Line:	68
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	69
	; >>>>> YKIdleCount=YKIdleCount+1; 
	mov	ax, word [YKIdleCount]
	inc	ax
	mov	word [YKIdleCount], ax
	; >>>>> Line:	70
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_19:
	jmp	L_yakc_18
L_yakc_20:
	mov	sp, bp
	pop	bp
	ret
L_yakc_16:
	push	bp
	mov	bp, sp
	jmp	L_yakc_17
	ALIGN	2
YKNewTask:
	; >>>>> Line:	74
	; >>>>> else 
	jmp	L_yakc_22
L_yakc_23:
	; >>>>> Line:	78
	; >>>>> taskStack = ((int *)taskStack) - 1; 
	mov	ax, word [bp+6]
	sub	ax, 2
	mov	word [bp+6], ax
	; >>>>> Line:	81
	; >>>>> tmp = YKAvailTCBList; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	; >>>>> Line:	82
	; >>>>> YKAvailTCBList = tmp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKAvailTCBList], ax
	; >>>>> Line:	85
	; >>>>> tmp->priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	86
	; >>>>> tmp->delay = 0; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	88
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	91
	; >>>>> if (YKRdyList == 0){ 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakc_24
	; >>>>> Line:	92
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	; >>>>> Line:	93
	; >>>>> tmp->next = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	94
	; >>>>> tmp->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	jmp	L_yakc_25
L_yakc_24:
	; >>>>> Line:	97
	; >>>>> tmp2 = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	98
	; >>>>> while (tmp2->priority < tmp->priority){ 
	jmp	L_yakc_27
L_yakc_26:
	; >>>>> Line:	99
	; >>>>> tmp2 = tmp2->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_27:
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-2]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_26
L_yakc_28:
	; >>>>> Line:	101
	; >>>>> if (tmp2->prev == 0) 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_29
	; >>>>> Line:	102
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_30
L_yakc_29:
	; >>>>> Line:	104
	; >>>>> tmp2->prev->next = tmp; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_30:
	; >>>>> Line:	105
	; >>>>> tmp->prev = tmp2->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	106
	; >>>>> tmp- 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	107
	; >>>>> tmp2->prev = tmp; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_25:
	; >>>>> Line:	111
	; >>>>> tmp->stackptr = taskStack; 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	114
	; >>>>> tmp->stackptr = tmp->stackptr - 11; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, 22
	mov	word [si], ax
	; >>>>> Line:	115
	; >>>>> for(i=11; i>=0;i--){ 
	mov	word [bp-6], 11
	jmp	L_yakc_32
L_yakc_31:
	; >>>>> Line:	116
	; >>>>> if(i == 11){ 
	cmp	word [bp-6], 11
	jne	L_yakc_35
	; >>>>> Line:	117
	; >>>>> *(tmp->stackptr+i) = 0x200; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 512
	jmp	L_yakc_36
L_yakc_35:
	; >>>>> Line:	119
	; >>>>> else if(i == 10){ 
	cmp	word [bp-6], 10
	jne	L_yakc_37
	; >>>>> Line:	120
	; >>>>> *(tmp->stackptr+i) = 0; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 0
	jmp	L_yakc_38
L_yakc_37:
	; >>>>> Line:	122
	; >>>>> else if(i == 9){ 
	cmp	word [bp-6], 9
	jne	L_yakc_39
	; >>>>> Line:	123
	; >>>>> *(tmp->stackptr+i) = (int)task; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	ax, word [bp+4]
	mov	word [si], ax
	jmp	L_yakc_40
L_yakc_39:
	; >>>>> Line:	126
	; >>>>> *(tmp->stackptr+i) = 0; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 0
L_yakc_40:
L_yakc_38:
L_yakc_36:
L_yakc_34:
	dec	word [bp-6]
L_yakc_32:
	cmp	word [bp-6], 0
	jge	L_yakc_31
L_yakc_33:
	; >>>>> Line:	131
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_22:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_23
L_yakc_42:
	DB	"Start Run and call scheduler",0xA,0
	ALIGN	2
YKRun:
	; >>>>> Line:	135
	; >>>>> void YKRun(void){ 
	jmp	L_yakc_43
L_yakc_44:
	; >>>>> Line:	136
	; >>>>> printString("Start Run and call scheduler\n"); 
	mov	ax, L_yakc_42
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	137
	; >>>>> run_flag = 1; 
	mov	byte [run_flag], 1
	; >>>>> Line:	138
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_43:
	push	bp
	mov	bp, sp
	jmp	L_yakc_44
	ALIGN	2
YKScheduler:
	; >>>>> Line:	141
	; >>>>> tr); 
	jmp	L_yakc_46
L_yakc_47:
	; >>>>> Line:	149
	; >>>>> highest_priority_task = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	150
	; >>>>> currentlyRunning = TKCurrentlyRunning; 
	mov	ax, word [TKCurrentlyRunning]
	mov	word [bp-4], ax
	; >>>>> Line:	152
	; >>>>> if(!run_flag || (TKCurrentlyRunning == highest_priority_task)){ 
	mov	al, byte [run_flag]
	test	al, al
	je	L_yakc_49
	mov	ax, word [bp-2]
	cmp	ax, word [TKCurrentlyRunning]
	jne	L_yakc_48
L_yakc_49:
	; >>>>> Line:	153
	; >>>>> return; 
	jmp	L_yakc_50
L_yakc_48:
	; >>>>> Line:	156
	; >>>>> YKCtxSwCount = YKCtxSwCount + 1; 
	mov	ax, word [YKCtxSwCount]
	inc	ax
	mov	word [YKCtxSwCount], ax
	; >>>>> Line:	157
	; >>>>> TKCurrentlyRunning = highest_priority_task; 
	mov	ax, word [bp-2]
	mov	word [TKCurrentlyRunning], ax
	; >>>>> Line:	158
	; >>>>> if(!save_flag){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_51
	; >>>>> Line:	160
	; >>>>> YKDispatcherNSave(highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	call	YKDispatcherNSave
	add	sp, 2
	jmp	L_yakc_52
L_yakc_51:
	; >>>>> Line:	165
	; >>>>> YKDispatcherSave(&(currentlyRunning->stackptr), highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	push	word [bp-4]
	call	YKDispatcherSave
	add	sp, 4
L_yakc_52:
L_yakc_50:
	mov	sp, bp
	pop	bp
	ret
L_yakc_46:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_47
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	171
	; >>>>> RDepth = 
	jmp	L_yakc_54
L_yakc_55:
	; >>>>> Line:	173
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	176
	; >>>>> if(count == 0){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_56
	; >>>>> Line:	177
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	178
	; >>>>> return; 
	jmp	L_yakc_57
L_yakc_56:
	; >>>>> Line:	182
	; >>>>> ready = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	184
	; >>>>> YKRdyList = ready->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	185
	; >>>>> ready->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	187
	; >>>>> ready->next = YKDelayList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKDelayList]
	mov	word [si], ax
	; >>>>> Line:	188
	; >>>>> YKDelayList = ready; 
	mov	ax, word [bp-2]
	mov	word [YKDelayList], ax
	; >>>>> Line:	189
	; >>>>> ready->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	190
	; >>>>> if(ready->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_58
	; >>>>> Line:	191
	; >>>>> ready->next->prev=ready; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_58:
	; >>>>> Line:	193
	; >>>>> ready->delay = count; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	194
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	195
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_57:
	mov	sp, bp
	pop	bp
	ret
L_yakc_54:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_55
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	199
	; >>>>> void YKEnterISR(void){ 
	jmp	L_yakc_60
L_yakc_61:
	; >>>>> Line:	200
	; >>>>> YKISRDepth = YKISRDepth + 1; 
	mov	ax, word [YKISRDepth]
	inc	ax
	mov	word [YKISRDepth], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_60:
	push	bp
	mov	bp, sp
	jmp	L_yakc_61
	ALIGN	2
YKExitISR:
	; >>>>> Line:	204
	; >>>>> void YKExitISR(void){ 
	jmp	L_yakc_63
L_yakc_64:
	; >>>>> Line:	205
	; >>>>> YKISRDepth = YKISRDepth - 1; 
	mov	ax, word [YKISRDepth]
	dec	ax
	mov	word [YKISRDepth], ax
	; >>>>> Line:	207
	; >>>>> if(YKISRDepth = 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_65
	; >>>>> Line:	208
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_65:
	mov	sp, bp
	pop	bp
	ret
L_yakc_63:
	push	bp
	mov	bp, sp
	jmp	L_yakc_64
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	212
	; >>>>> void YKTickHandler(void){ 
	jmp	L_yakc_67
L_yakc_68:
	; >>>>> Line:	215
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	216
	; >>>>> YKTickNum = YKTickNum + 1; 
	mov	ax, word [YKTickNum]
	inc	ax
	mov	word [YKTickNum], ax
	; >>>>> Line:	221
	; >>>>> tempDelay = YKDelayList; 
	mov	ax, word [YKDelayList]
	mov	word [bp-2], ax
	; >>>>> Line:	223
	; >>>>> while(tempDelay != 0){ 
	jmp	L_yakc_70
L_yakc_69:
	; >>>>> Line:	224
	; >>>>> tempNext = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
	; >>>>> Line:	225
	; >>>>> tempDelay->delay = tempDelay->delay - 1; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [si]
	dec	ax
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], ax
	; >>>>> Line:	226
	; >>>>> if(tempDelay->delay <= 0){ 
	mov	si, word [bp-2]
	add	si, 6
	cmp	word [si], 0
	jg	L_yakc_72
	; >>>>> Line:	228
	; >>>>> if(tempDelay->prev == 0){ 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_73
	; >>>>> Line:	229
	; >>>>> YKDelayList = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKDelayList], ax
	jmp	L_yakc_74
L_yakc_73:
	; >>>>> Line:	232
	; >>>>> tempDelay->prev->next = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	di, word [bp-2]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_74:
	; >>>>> Line:	234
	; >>>>> if(tempDelay->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_75
	; >>>>> Line:	235
	; >>>>> eate(int initialValue){ 
	mov	si, word [bp-2]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_75:
	; >>>>> Line:	238
	; >>>>> tempReady = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	239
	; >>>>> while(tempReady->priority < tempDelay->priority){ 
	jmp	L_yakc_77
L_yakc_76:
	; >>>>> Line:	240
	; >>>>> tempReady = tempReady->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_77:
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-2]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_76
L_yakc_78:
	; >>>>> Line:	242
	; >>>>> if(tempReady->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_79
	; >>>>> Line:	243
	; >>>>> YKRdyList = tempDelay; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_80
L_yakc_79:
	; >>>>> Line:	246
	; >>>>> tempReady->prev->next = tempDelay; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_80:
	; >>>>> Line:	249
	; >>>>> tempDelay->prev = tempReady->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	250
	; >>>>> tempDelay->next = tempReady; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	251
	; >>>>> tempReady->prev = tempDelay; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_72:
	; >>>>> Line:	253
	; >>>>> tempDelay = tempNext; 
	mov	ax, word [bp-6]
	mov	word [bp-2], ax
L_yakc_70:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_69
L_yakc_71:
	; >>>>> Line:	255
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_67:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_68
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	258
	; >>>>> YKSEM* YKSemCreate(int initialValue){ 
	jmp	L_yakc_82
L_yakc_83:
	; >>>>> Line:	260
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	261
	; >>>>> i = 0; 
	mov	word [bp-2], 0
	; >>>>> Line:	262
	; >>>>> while(YKSemArray[i].active){ 
	jmp	L_yakc_85
L_yakc_84:
	; >>>>> Line:	263
	; >>>>> i = i+1; 
	mov	ax, word [bp-2]
	inc	ax
	mov	word [bp-2], ax
L_yakc_85:
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_84
L_yakc_86:
	; >>>>> Line:	267
	; >>>>> YKSemArray[i].active = 1; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	; >>>>> Line:	268
	; >>>>> YKSemArray[i].val = initialValue; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	si, ax
	add	si, YKSemArray
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	269
	; >>>>> YKSemArray[i].id = i; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	271
	; >>>>> return &(YKSemArray[i]); 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
L_yakc_87:
	mov	sp, bp
	pop	bp
	ret
L_yakc_82:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_83
	ALIGN	2
YKSemPend:
	; >>>>> Line:	281
	; >>>>> void YKSemPend(YKSEM *semaphore){ 
	jmp	L_yakc_89
L_yakc_90:
	; >>>>> Line:	284
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	285
	; >>>>> semaphore->val = semaphore->val - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	mov	word [si], ax
	; >>>>> Line:	286
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	288
	; >>>>> if (semaphore->val >= 0){ return; } 
	mov	si, word [bp+4]
	cmp	word [si], 0
	jl	L_yakc_91
	; >>>>> Line:	288
	; >>>>> if (semaphore->val >= 0){ return; } 
	jmp	L_yakc_92
L_yakc_91:
	; >>>>> Line:	290
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	291
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	292
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	293
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	294
	; >>>>> readyTask->next = YK 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKSemWaitList]
	mov	word [si], ax
	; >>>>> Line:	295
	; >>>>> YKSemWaitList = readyTask; 
	mov	ax, word [bp-2]
	mov	word [YKSemWaitList], ax
	; >>>>> Line:	296
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	298
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_93
	; >>>>> Line:	299
	; >>>>> readyTask->next->prev = readyTask; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_93:
	; >>>>> Line:	302
	; >>>>> readyTask->semWait = semaphore; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	304
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	305
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_92:
	mov	sp, bp
	pop	bp
	ret
L_yakc_89:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_90
	ALIGN	2
YKSemPost:
	; >>>>> Line:	319
	; >>>>> void YKSemPost(YKSEM *semaphore){ 
	jmp	L_yakc_95
L_yakc_96:
	; >>>>> Line:	321
	; >>>>> unSuspTask = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	322
	; >>>>> semWaiting = YKSemWaitList; 
	mov	ax, word [YKSemWaitList]
	mov	word [bp-2], ax
	; >>>>> Line:	324
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	325
	; >>>>> semaphore->val = semaphore->val + 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	inc	ax
	mov	word [si], ax
	; >>>>> Line:	328
	; >>>>> while(semWaiting != 0){ 
	jmp	L_yakc_98
L_yakc_97:
	; >>>>> Line:	330
	; >>>>> if(semWaiting->semWait == semaphore){ 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_100
	; >>>>> Line:	331
	; >>>>> if((unSuspTask == 0)  
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_102
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_101
L_yakc_102:
	; >>>>> Line:	332
	; >>>>> unSuspTask = semWaiting; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
L_yakc_101:
L_yakc_100:
	; >>>>> Line:	335
	; >>>>> semWaiting = semWaiting->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_98:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_97
L_yakc_99:
	; >>>>> Line:	338
	; >>>>> if(unSuspTask == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_103
	; >>>>> Line:	339
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	340
	; >>>>> return; 
	jmp	L_yakc_104
L_yakc_103:
	; >>>>> Line:	343
	; >>>>> if(unSuspTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_105
	; >>>>> Line:	344
	; >>>>> YKSemWaitList = unSuspTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKSemWaitList], ax
	jmp	L_yakc_106
L_yakc_105:
	; >>>>> Line:	347
	; >>>>> unSuspTask->prev->next = unSuspTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_106:
	; >>>>> Line:	350
	; >>>>> if (unSuspTask->next != 0){ 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_107
	; >>>>> Line:	351
	; >>>>> unSuspTask->next->prev = unSuspTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_107:
	; >>>>> Line:	355
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	356
	; >>>>> while (readyTask->priority < unSuspTask->priority){ 
	jmp	L_yakc_109
L_yakc_108:
	; >>>>> Line:	357
	; >>>>> { 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_109:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_108
L_yakc_110:
	; >>>>> Line:	359
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_111
	; >>>>> Line:	360
	; >>>>> YKRdyList = unSuspTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_112
L_yakc_111:
	; >>>>> Line:	363
	; >>>>> readyTask->prev->next = unSuspTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_112:
	; >>>>> Line:	365
	; >>>>> unSuspTask->prev = readyTask->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	366
	; >>>>> unSuspTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	367
	; >>>>> readyTask->prev = unSuspTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	369
	; >>>>> unSuspTask->semWait = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	371
	; >>>>> if( YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_113
	; >>>>> Line:	372
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_113:
	; >>>>> Line:	374
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_104:
	; >>>>> Line:	375
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_95:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_96
	ALIGN	2
queueInsert:
	; >>>>> Line:	378
	; >>>>> void queueInsert(YKQ* queue, void* msg){ 
	jmp	L_yakc_115
L_yakc_116:
	; >>>>> Line:	379
	; >>>>> queue->base_addr[queue->head] = msg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	380
	; >>>>> if(queue->head < queue->size){ 
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_117
	; >>>>> Line:	381
	; >>>>> queue->head += 1; 
	mov	si, word [bp+4]
	add	si, 6
	inc	word [si]
	jmp	L_yakc_118
L_yakc_117:
	; >>>>> Line:	384
	; >>>>> queue->head = 0; 
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], 0
L_yakc_118:
	mov	sp, bp
	pop	bp
	ret
L_yakc_115:
	push	bp
	mov	bp, sp
	jmp	L_yakc_116
	ALIGN	2
queueRemove:
	; >>>>> Line:	388
	; >>>>> void* queueRemove(YKQ* queue){ 
	jmp	L_yakc_120
L_yakc_121:
	; >>>>> Line:	390
	; >>>>> msg = *(queue->base_addr + queue->tail); 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	391
	; >>>>> if(queue->tail > 0){ 
	mov	si, word [bp+4]
	add	si, 8
	cmp	word [si], 0
	jle	L_yakc_122
	; >>>>> Line:	392
	; >>>>> queue->head -= 1; 
	mov	si, word [bp+4]
	add	si, 6
	dec	word [si]
	jmp	L_yakc_123
L_yakc_122:
	; >>>>> Line:	395
	; >>>>> queue->head = queue->size - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	add	si, 6
	mov	word [si], ax
L_yakc_123:
	; >>>>> Line:	397
	; >>>>> return msg; 
	mov	ax, word [bp-2]
L_yakc_124:
	mov	sp, bp
	pop	bp
	ret
L_yakc_120:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_121
	ALIGN	2
YKQCreate:
	; >>>>> Line:	401
	; >>>>> YKQ *YKQCreate(void **start, unsigned size){ 
	jmp	L_yakc_126
L_yakc_127:
	; >>>>> Line:	410
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	411
	; >>>>> for (i = 0; YKQueueArray[i].base_addr; i++){}; 
	mov	word [bp-2], 0
	jmp	L_yakc_129
L_yakc_128:
L_yakc_131:
	; >>>>> Line:	411
	; >>>>> for (i = 0; YKQueueArray[i].base_addr; i++){}; 
	inc	word [bp-2]
L_yakc_129:
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 4
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_128
L_yakc_130:
	; >>>>> Line:	413
	; >>>>> YKQueueArray[i].base_addr = start; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	414
	; >>>>> YKQueueArray[i].length = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	415
	; >>>>> YKQueueArray[i].size = size; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	mov	si, ax
	add	si, YKQueueArray
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	416
	; >>>>> YKQueueArray[i].tail = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	417
	; >>>>> YKQueueArray[i].head = 0; 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
	mov	si, ax
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	418
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	419
	; >>>>> ->tai 
	mov	ax, word [bp-2]
	mov	cx, 10
	imul	cx
	add	ax, YKQueueArray
L_yakc_132:
	mov	sp, bp
	pop	bp
	ret
L_yakc_126:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_127
	ALIGN	2
YKQPend:
	; >>>>> Line:	429
	; >>>>> void *YKQPend(YKQ *queue){ 
	jmp	L_yakc_134
L_yakc_135:
	; >>>>> Line:	459
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	460
	; >>>>> if(queue->length == 0){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_136
	; >>>>> Line:	463
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	464
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	465
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	466
	; >>>>> readyTask->next = YKQWaitList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKQWaitList]
	mov	word [si], ax
	; >>>>> Line:	467
	; >>>>> YKQWaitList = readyTask; 
	mov	ax, word [bp-2]
	mov	word [YKQWaitList], ax
	; >>>>> Line:	468
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	470
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_137
	; >>>>> Line:	471
	; >>>>> readyTask->next->prev = readyTask; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_137:
	; >>>>> Line:	474
	; >>>>> readyTask->queueWait = queue; 
	mov	si, word [bp-2]
	add	si, 14
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	475
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_136:
	; >>>>> Line:	477
	; >>>>> msg = *(queue->base_addr + queue->tai 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	478
	; >>>>> queue->length = queue->length - 1; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	dec	ax
	mov	si, word [bp+4]
	add	si, 2
	mov	word [si], ax
	; >>>>> Line:	480
	; >>>>> if((queue->tail + 1) < queue->size){ 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	mov	dx, word [si]
	cmp	dx, ax
	jle	L_yakc_138
	; >>>>> Line:	481
	; >>>>> queue->tail = queue->tail + 1; 
	add	si, 8
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], ax
	jmp	L_yakc_139
L_yakc_138:
	; >>>>> Line:	484
	; >>>>> queue->tail = 0; 
	mov	si, word [bp+4]
	add	si, 8
	mov	word [si], 0
L_yakc_139:
	; >>>>> Line:	487
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	488
	; >>>>> return msg; 
	mov	ax, word [bp-4]
L_yakc_140:
	mov	sp, bp
	pop	bp
	ret
L_yakc_134:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_135
	ALIGN	2
YKQPost:
	; >>>>> Line:	503
	; >>>>> int YKQPost(YKQ *queue, void *msg){ 
	jmp	L_yakc_142
L_yakc_143:
	; >>>>> Line:	505
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	507
	; >>>>> if((queue->length + 1) == queue->size){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	mov	dx, word [si]
	cmp	dx, ax
	jne	L_yakc_144
	; >>>>> Line:	508
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_yakc_145
L_yakc_144:
	; >>>>> Line:	513
	; >>>>> unWaitTask = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	514
	; >>>>> queueWait = YKQWaitList; 
	mov	ax, word [YKQWaitList]
	mov	word [bp-2], ax
	; >>>>> Line:	517
	; >>>>> queue->base_addr[queue->head] = msg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	518
	; >>>>> queue->length = queue->length + 1; 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 2
	mov	word [si], ax
	; >>>>> Line:	519
	; >>>>> if((queue->head + 1) < q 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	mov	dx, word [si]
	cmp	dx, ax
	jle	L_yakc_146
	; >>>>> Line:	520
	; >>>>> queue->head = queue->head + 1; 
	add	si, 6
	mov	ax, word [si]
	inc	ax
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], ax
	jmp	L_yakc_147
L_yakc_146:
	; >>>>> Line:	523
	; >>>>> queue->head = 0; 
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], 0
L_yakc_147:
	; >>>>> Line:	526
	; >>>>> while(queueWait != 0){ 
	jmp	L_yakc_149
L_yakc_148:
	; >>>>> Line:	528
	; >>>>> if(queueWait->queueWait == queue){ 
	mov	si, word [bp-2]
	add	si, 14
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_151
	; >>>>> Line:	529
	; >>>>> if((unWaitTask == 0) || (queueWait->priority < unWaitTask->priority)){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_153
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_152
L_yakc_153:
	; >>>>> Line:	530
	; >>>>> unWaitTask = queueWait; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
L_yakc_152:
L_yakc_151:
	; >>>>> Line:	533
	; >>>>> queueWait = queueWait->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_149:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_148
L_yakc_150:
	; >>>>> Line:	537
	; >>>>> if(unWaitTask == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_154
	; >>>>> Line:	538
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	539
	; >>>>> return 1; 
	mov	ax, 1
	jmp	L_yakc_145
L_yakc_154:
	; >>>>> Line:	543
	; >>>>> if(unWaitTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_155
	; >>>>> Line:	544
	; >>>>> YKQWaitList = unWaitTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKQWaitList], ax
	jmp	L_yakc_156
L_yakc_155:
	; >>>>> Line:	547
	; >>>>> unWaitTask->prev->next = unWaitTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_156:
	; >>>>> Line:	550
	; >>>>> if (un 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_157
	; >>>>> Line:	551
	; >>>>> unWaitTask->next->prev = unWaitTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_157:
	; >>>>> Line:	554
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	555
	; >>>>> while (readyTask->priority < unWaitTask->priority){ 
	jmp	L_yakc_159
L_yakc_158:
	; >>>>> Line:	556
	; >>>>> readyTask = readyTask->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_159:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_158
L_yakc_160:
	; >>>>> Line:	558
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_161
	; >>>>> Line:	559
	; >>>>> YKRdyList = unWaitTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_162
L_yakc_161:
	; >>>>> Line:	562
	; >>>>> readyTask->prev->next = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_162:
	; >>>>> Line:	564
	; >>>>> unWaitTask->prev = readyTask->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	565
	; >>>>> unWaitTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	566
	; >>>>> readyTask->prev = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	568
	; >>>>> unWaitTask->queueWait = 0; 
	mov	si, word [bp-4]
	add	si, 14
	mov	word [si], 0
	; >>>>> Line:	570
	; >>>>> if(YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_163
	; >>>>> Line:	571
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_163:
	; >>>>> Line:	573
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	574
	; >>>>> return 1; 
	mov	ax, 1
L_yakc_145:
	mov	sp, bp
	pop	bp
	ret
L_yakc_142:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_143
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKDelayList:
	TIMES	2 db 0
YKSemWaitList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	160 db 0
idleStack:
	TIMES	512 db 0
YKISRDepth:
	TIMES	2 db 0
YKSemArray:
	TIMES	114 db 0
YKQueueArray:
	TIMES	20 db 0
YKQWaitList:
	TIMES	2 db 0
TKCurrentlyRunning:
	TIMES	2 db 0
;Assemble funtcions

YKEnterMutex:                   ; Disables interrupts
	cli	                          ; clear interrupt flag
	ret


YKExitMutex:                    ; Enables Interrupts
	sti	                          ; set interrupt flag
	ret

YKDispatcherNSave:   		; Dispatcher that saves to mem/stack

  cli

	push bp			; Push the base pointer onto the stack
	mov bp, sp		; set the current base pointer to be the stack pointer

	; Get the sp values to restore and save them to sp
	mov sp, word[bp+4]			; getting first arg (highest priority task sp)

	;mov	al, 0x20
	;out 	0x20, al

	; Pop register values off the stack
	pop ES
	pop DS
	pop DI
	pop SI
	pop BP
	pop DX
	pop CX
	pop BX
	pop AX

	iret

YKDispatcherSave:   		; Dispatcher that saves to mem/stack

  cli

	push bp
	mov bp, sp

	mov AX, [bp+2]

	pop bp
	add sp, 2

	; Push flags, CS, and IP to the stack
	pushf

	; This is something about the flags that Ian told me to do
	;push BX
	;add sp, 2
	;pop BX
	;or BX, 0x200
	;push BX
	;sub sp, 2
	;pop BX

	push CS
	push AX
	;push word[bp+2]

	; Push all register values to the stack
	push AX
	push BX
	push CX
	push DX
	push BP
	push SI
	push DI
	push DS
	push ES

	; Move bp back to its original value
	mov bp, sp
	add bp, 20

	; Store the save sp to si
	mov si, word [bp+4] 			; getting first arg (sp)
	mov word [si], sp

restore_context:

	; Save the sp and ss values to restore to sp and ss
	mov sp, word[bp+6]			; getting second arg

	;mov	al, 0x20
	;out 	0x20, al

	; Pop register values back off the stack
	pop ES
	pop DS
	pop DI
	pop SI
	pop BP
	pop DX
	pop CX
	pop BX
	pop AX
	iret
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab6_app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab6_app_5:
	DB	"Max: ",0
L_lab6_app_4:
	DB	"Min: ",0
L_lab6_app_3:
	DB	0x9,0
L_lab6_app_2:
	DB	"Ticks: ",0
L_lab6_app_1:
	DB	"! Dropped msgs: tick ",0
	ALIGN	2
ATask:
	; >>>>> Line:	26
	; >>>>> { 
	jmp	L_lab6_app_6
L_lab6_app_7:
	; >>>>> Line:	30
	; >>>>> min = 100; 
	mov	word [bp-4], 100
	; >>>>> Line:	31
	; >>>>> max = 0; 
	mov	word [bp-6], 0
	; >>>>> Line:	32
	; >>>>> count = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	34
	; >>>>> while (1) 
	jmp	L_lab6_app_9
L_lab6_app_8:
	; >>>>> Line:	36
	; >>>>> tmp = (struct msg *) YKQPend(MsgQPtr); 
	push	word [MsgQPtr]
	call	YKQPend
	add	sp, 2
	mov	word [bp-2], ax
	; >>>>> Line:	44
	; >>>>> if (tmp->tick != count+1) 
	mov	ax, word [bp-8]
	inc	ax
	mov	si, word [bp-2]
	mov	dx, word [si]
	cmp	dx, ax
	je	L_lab6_app_11
	; >>>>> Line:	46
	; >>>>> print("! Dropped msgs: tick ", 21); 
	mov	ax, 21
	push	ax
	mov	ax, L_lab6_app_1
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	47
	; >>>>> if (tmp->tick - (count+1) > 1) { 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, word [bp-8]
	dec	ax
	cmp	ax, 1
	jle	L_lab6_app_12
	; >>>>> Line:	48
	; >>>>> printInt(count+1); 
	mov	ax, word [bp-8]
	inc	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	49
	; >>>>> printChar('-'); 
	mov	al, 45
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	50
	; >>>>> printInt(tmp->tick-1); 
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	51
	; >>>>> printNe 
	call	printNewLine
	jmp	L_lab6_app_13
L_lab6_app_12:
	; >>>>> Line:	54
	; >>>>> printInt(tmp->tick-1); 
	mov	si, word [bp-2]
	mov	ax, word [si]
	dec	ax
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	55
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab6_app_13:
L_lab6_app_11:
	; >>>>> Line:	60
	; >>>>> count = tmp->tick; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	mov	word [bp-8], ax
	; >>>>> Line:	63
	; >>>>> if (tmp->data < min) 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-4]
	cmp	ax, word [si]
	jle	L_lab6_app_14
	; >>>>> Line:	64
	; >>>>> min = tmp->data; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-4], ax
L_lab6_app_14:
	; >>>>> Line:	65
	; >>>>> if (tmp->data > max) 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [bp-6]
	cmp	ax, word [si]
	jge	L_lab6_app_15
	; >>>>> Line:	66
	; >>>>> max = tmp->data; 
	mov	si, word [bp-2]
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-6], ax
L_lab6_app_15:
	; >>>>> Line:	69
	; >>>>> print("Ticks: ", 7); 
	mov	ax, 7
	push	ax
	mov	ax, L_lab6_app_2
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	70
	; >>>>> printInt(count); 
	push	word [bp-8]
	call	printInt
	add	sp, 2
	; >>>>> Line:	71
	; >>>>> print("\t", 1); 
	mov	ax, 1
	push	ax
	mov	ax, L_lab6_app_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	72
	; >>>>> print("Min: ", 5); 
	mov	ax, 5
	push	ax
	mov	ax, L_lab6_app_4
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	73
	; >>>>> printInt(min); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	74
	; >>>>> print("\t", 1); 
	mov	ax, 1
	push	ax
	mov	ax, L_lab6_app_3
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	75
	; >>>>> print("Max: ", 5); 
	mov	ax, 5
	push	ax
	mov	ax, L_lab6_app_5
	push	ax
	call	print
	add	sp, 4
	; >>>>> Line:	76
	; >>>>> printInt(max); 
	push	word [bp-6]
	call	printInt
	add	sp, 2
	; >>>>> Line:	77
	; >>>>> nt + 5) break; 
	call	printNewLine
L_lab6_app_9:
	jmp	L_lab6_app_8
L_lab6_app_10:
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_6:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab6_app_7
	ALIGN	2
BTask:
	; >>>>> Line:	82
	; >>>>> { 
	jmp	L_lab6_app_17
L_lab6_app_18:
	; >>>>> Line:	86
	; >>>>> curval = 1001; 
	mov	word [bp-4], 1001
	; >>>>> Line:	87
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
	; >>>>> Line:	89
	; >>>>> while (1) 
	jmp	L_lab6_app_20
L_lab6_app_19:
	; >>>>> Line:	91
	; >>>>> YKDelayTask(2); 
	mov	ax, 2
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	93
	; >>>>> if (GlobalFlag == 1) 
	cmp	word [GlobalFlag], 1
	jne	L_lab6_app_22
	; >>>>> Line:	95
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	96
	; >>>>> busycount = YKTickNum; 
	mov	ax, word [YKTickNum]
	mov	word [bp-2], ax
	; >>>>> Line:	97
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	99
	; >>>>> while (1) 
	jmp	L_lab6_app_24
L_lab6_app_23:
	; >>>>> Line:	101
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	102
	; >>>>> tickNum = YKTickNum; 
	mov	ax, word [YKTickNum]
	mov	word [bp-12], ax
	; >>>>> Line:	103
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	104
	; >>>>> if(tickNum >= busycount + 5) break; 
	mov	ax, word [bp-2]
	add	ax, 5
	mov	dx, word [bp-12]
	cmp	dx, ax
	jb	L_lab6_app_26
	; >>>>> Line:	104
	; >>>>> if(tickNum >= busycount + 5) break; 
	jmp	L_lab6_app_25
L_lab6_app_26:
	; >>>>> Line:	106
	; >>>>>  
	add	word [bp-4], 2
	; >>>>> Line:	107
	; >>>>> flag = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	108
	; >>>>> for (j = 3; (j*j) < curval; j += 2) 
	mov	word [bp-6], 3
	jmp	L_lab6_app_28
L_lab6_app_27:
	; >>>>> Line:	110
	; >>>>> if (curval % j == 0) 
	mov	ax, word [bp-4]
	cwd
	idiv	word [bp-6]
	mov	ax, dx
	test	ax, ax
	jne	L_lab6_app_31
	; >>>>> Line:	112
	; >>>>> flag = 1; 
	mov	word [bp-8], 1
	; >>>>> Line:	113
	; >>>>> break; 
	jmp	L_lab6_app_29
L_lab6_app_31:
L_lab6_app_30:
	add	word [bp-6], 2
L_lab6_app_28:
	mov	ax, word [bp-6]
	imul	word [bp-6]
	mov	dx, word [bp-4]
	cmp	dx, ax
	jg	L_lab6_app_27
L_lab6_app_29:
	; >>>>> Line:	116
	; >>>>> if (!flag) 
	mov	ax, word [bp-8]
	test	ax, ax
	jne	L_lab6_app_32
	; >>>>> Line:	118
	; >>>>> printChar('.'); 
	mov	al, 46
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	119
	; >>>>> if (++chcount > 75) 
	mov	ax, word [bp-10]
	inc	ax
	mov	word [bp-10], ax
	cmp	ax, 75
	jle	L_lab6_app_33
	; >>>>> Line:	121
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	122
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
L_lab6_app_33:
L_lab6_app_32:
L_lab6_app_24:
	jmp	L_lab6_app_23
L_lab6_app_25:
	; >>>>> Line:	126
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	127
	; >>>>> chcount = 0; 
	mov	word [bp-10], 0
	; >>>>> Line:	128
	; >>>>> GlobalFlag = 0; 
	mov	word [GlobalFlag], 0
L_lab6_app_22:
L_lab6_app_20:
	jmp	L_lab6_app_19
L_lab6_app_21:
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_17:
	push	bp
	mov	bp, sp
	sub	sp, 12
	jmp	L_lab6_app_18
L_lab6_app_39:
	DB	"% >>>>>",0xD,0xA,0
L_lab6_app_38:
	DB	", CPU usage: ",0
L_lab6_app_37:
	DB	"<<<<< Context switches: ",0
L_lab6_app_36:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab6_app_35:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
STask:
	; >>>>> Line:	134
	; >>>>> { 
	jmp	L_lab6_app_40
L_lab6_app_41:
	; >>>>> Line:	138
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	139
	; >>>>> printString("Welcome to the YAK kernel\r\n"); 
	mov	ax, L_lab6_app_35
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	140
	; >>>>> printString("Determining CPU capacity\r\n"); 
	mov	ax, L_lab6_app_36
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	141
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	142
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	143
	; >>>>> YKDelayTask(5); 
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	144
	; >>>>> max = YKIdleCount / 25; 
	mov	ax, word [YKIdleCount]
	xor	dx, dx
	mov	cx, 25
	div	cx
	mov	word [bp-2], ax
	; >>>>> Line:	145
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	147
	; >>>>> YKNewTask(BTask, (void *) &BTaskStk[512], 10); 
	mov	al, 10
	push	ax
	mov	ax, (BTaskStk+1024)
	push	ax
	mov	ax, BTask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	148
	; >>>>> = 0; 
	mov	al, 20
	push	ax
	mov	ax, (ATaskStk+1024)
	push	ax
	mov	ax, ATask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	150
	; >>>>> while (1) 
	jmp	L_lab6_app_43
L_lab6_app_42:
	; >>>>> Line:	152
	; >>>>> YKDelayTask(20); 
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	154
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	155
	; >>>>> switchCount = YKCtxSwCount; 
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	; >>>>> Line:	156
	; >>>>> idleCount = YKIdleCount; 
	mov	ax, word [YKIdleCount]
	mov	word [bp-6], ax
	; >>>>> Line:	157
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	159
	; >>>>> printString("<<<<< Context switches: "); 
	mov	ax, L_lab6_app_37
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	160
	; >>>>> printInt((int)switchCount); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	161
	; >>>>> printString(", CPU usage: "); 
	mov	ax, L_lab6_app_38
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	162
	; >>>>> tmp = (int) (idleCount/max); 
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	; >>>>> Line:	163
	; >>>>> printInt(100-tmp); 
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	164
	; >>>>> printString("% >>>>>\r\n"); 
	mov	ax, L_lab6_app_39
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	166
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	167
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	168
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	169
	; >>>>>  
	call	YKExitMutex
L_lab6_app_43:
	jmp	L_lab6_app_42
L_lab6_app_44:
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_40:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab6_app_41
	ALIGN	2
main:
	; >>>>> Line:	174
	; >>>>> { 
	jmp	L_lab6_app_46
L_lab6_app_47:
	; >>>>> Line:	175
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	178
	; >>>>> GlobalFlag = 0; 
	mov	word [GlobalFlag], 0
	; >>>>> Line:	179
	; >>>>> MsgQPtr = YKQCreate(MsgQ, 10); 
	mov	ax, 10
	push	ax
	mov	ax, MsgQ
	push	ax
	call	YKQCreate
	add	sp, 4
	mov	word [MsgQPtr], ax
	; >>>>> Line:	180
	; >>>>> YKNewTask(STask, (void *) &STaskStk[512], 30); 
	mov	al, 30
	push	ax
	mov	ax, (STaskStk+1024)
	push	ax
	mov	ax, STask
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	183
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab6_app_46:
	push	bp
	mov	bp, sp
	jmp	L_lab6_app_47
	ALIGN	2
MsgArray:
	TIMES	80 db 0
ATaskStk:
	TIMES	1024 db 0
BTaskStk:
	TIMES	1024 db 0
STaskStk:
	TIMES	1024 db 0
GlobalFlag:
	TIMES	2 db 0
MsgQ:
	TIMES	20 db 0
MsgQPtr:
	TIMES	2 db 0
