; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
run_flag:
	DB	0
	ALIGN	2
YKInitialize:
	; >>>>> Line:	28
	; >>>>> void YKInitialize(void){ 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	30
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	31
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	32
	; >>>>> TKCurrentlyRunning = 0; 
	mov	word [TKCurrentlyRunning], 0
	; >>>>> Line:	33
	; >>>>> YKISRDepth = 0; 
	mov	word [YKISRDepth], 0
	; >>>>> Line:	37
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	40
	; >>>>> YKAvailTCBList = &(YKTCBArray[0]); 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	42
	; >>>>> for (i = 0; i < 9; i++) 
	mov	word [bp-2], 0
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	43
	; >>>>> YKTCBArray[i].next = &(YKTCBArray[i+1]); 
	mov	ax, word [bp-2]
	inc	ax
	mov	cx, 4
	shl	ax, cl
	add	ax, YKTCBArray
	mov	dx, word [bp-2]
	mov	cx, 4
	shl	dx, cl
	add	dx, YKTCBArray
	mov	si, dx
	add	si, 8
	mov	word [si], ax
L_yakc_6:
	inc	word [bp-2]
L_yakc_4:
	cmp	word [bp-2], 9
	jl	L_yakc_3
L_yakc_5:
	; >>>>> Line:	44
	; >>>>> YKTCBArray[9].next 
	mov	word [(152+YKTCBArray)], 0
	; >>>>> Line:	46
	; >>>>> for (i = 0; i < 19; i++){ 
	mov	word [bp-2], 0
	jmp	L_yakc_8
L_yakc_7:
	; >>>>> Line:	47
	; >>>>> YKSemArray[i].val = -10; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	si, ax
	add	si, YKSemArray
	mov	word [si], -10
	; >>>>> Line:	48
	; >>>>> YKSemArray[i].active = 0; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	49
	; >>>>> YKSemArray[i].id = i; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_10:
	inc	word [bp-2]
L_yakc_8:
	cmp	word [bp-2], 19
	jl	L_yakc_7
L_yakc_9:
	; >>>>> Line:	52
	; >>>>> YKNewTask(YKIdleTask, (void*)&idleStack[256], 100); 
	mov	al, 100
	push	ax
	mov	ax, (idleStack+512)
	push	ax
	mov	ax, YKIdleTask
	push	ax
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	55
	; >>>>> void YKIdleTask(void){ 
	jmp	L_yakc_12
L_yakc_13:
	; >>>>> Line:	56
	; >>>>> while(1){ 
	jmp	L_yakc_15
L_yakc_14:
	; >>>>> Line:	57
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	58
	; >>>>> YKIdleCount=YKIdleCount+1; 
	mov	ax, word [YKIdleCount]
	inc	ax
	mov	word [YKIdleCount], ax
	; >>>>> Line:	59
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_15:
	jmp	L_yakc_14
L_yakc_16:
	mov	sp, bp
	pop	bp
	ret
L_yakc_12:
	push	bp
	mov	bp, sp
	jmp	L_yakc_13
	ALIGN	2
YKNewTask:
	; >>>>> Line:	63
	; >>>>> void YKNewTask( void (*task)(void), void *taskStack, unsigned char priority){ 
	jmp	L_yakc_18
L_yakc_19:
	; >>>>> Line:	67
	; >>>>> taskStack = ((int *)taskStack) - 1; 
	mov	ax, word [bp+6]
	sub	ax, 2
	mov	word [bp+6], ax
	; >>>>> Line:	70
	; >>>>> tmp = YKAvailTCBList; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	; >>>>> Line:	71
	; >>>>> YKAvailTCBList = tmp->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKAvailTCBList], ax
	; >>>>> Line:	74
	; >>>>> tmp->priorit 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], ax
	; >>>>> Line:	75
	; >>>>> tmp->delay = 0; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	77
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	80
	; >>>>> if (YKRdyList == 0){ 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakc_20
	; >>>>> Line:	81
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	; >>>>> Line:	82
	; >>>>> tmp->next = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	83
	; >>>>> tmp->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	jmp	L_yakc_21
L_yakc_20:
	; >>>>> Line:	86
	; >>>>> tmp2 = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	87
	; >>>>> while (tmp2->priority < tmp->priority){ 
	jmp	L_yakc_23
L_yakc_22:
	; >>>>> Line:	88
	; >>>>> tmp2 = tmp2->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_23:
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-2]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_22
L_yakc_24:
	; >>>>> Line:	90
	; >>>>> if (tmp2->prev == 0) 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_25
	; >>>>> Line:	91
	; >>>>> YKRdyList = tmp; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_26
L_yakc_25:
	; >>>>> Line:	93
	; >>>>> tmp2->prev->next = tmp; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_26:
	; >>>>> Line:	94
	; >>>>> tmp->prev = tmp2->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	95
	; >>>>> tmp->next = tmp2; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	96
	; >>>>> tmp2->prev = tmp; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_21:
	; >>>>> Line:	100
	; >>>>> tmp->stackptr = taskStack; 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	103
	; >>>>> tmp->stackptr = tmp->stackptr - 11; 
	mov	si, word [bp-2]
	mov	ax, word [si]
	sub	ax, 22
	mov	word [si], ax
	; >>>>> Line:	104
	; >>>>> for(i=11; i>=0;i--){ 
	mov	word [bp-6], 11
	jmp	L_yakc_28
L_yakc_27:
	; >>>>> Line:	105
	; >>>>> if(i == 
	cmp	word [bp-6], 11
	jne	L_yakc_31
	; >>>>> Line:	106
	; >>>>> *(tmp->stackptr+i) = 0x200; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 512
	jmp	L_yakc_32
L_yakc_31:
	; >>>>> Line:	108
	; >>>>> else if(i == 10){ 
	cmp	word [bp-6], 10
	jne	L_yakc_33
	; >>>>> Line:	109
	; >>>>> *(tmp->stackptr+i) = 0; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 0
	jmp	L_yakc_34
L_yakc_33:
	; >>>>> Line:	111
	; >>>>> else if(i == 9){ 
	cmp	word [bp-6], 9
	jne	L_yakc_35
	; >>>>> Line:	112
	; >>>>> *(tmp->stackptr+i) = (int)task; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	ax, word [bp+4]
	mov	word [si], ax
	jmp	L_yakc_36
L_yakc_35:
	; >>>>> Line:	115
	; >>>>> *(tmp->stackptr+i) = 0; 
	mov	ax, word [bp-6]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp-2]
	add	si, word [di]
	mov	word [si], 0
L_yakc_36:
L_yakc_34:
L_yakc_32:
L_yakc_30:
	dec	word [bp-6]
L_yakc_28:
	cmp	word [bp-6], 0
	jge	L_yakc_27
L_yakc_29:
	; >>>>> Line:	120
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_18:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_19
L_yakc_38:
	DB	"Start Run and call scheduler",0xA,0
	ALIGN	2
YKRun:
	; >>>>> Line:	124
	; >>>>> void YKRun(void){ 
	jmp	L_yakc_39
L_yakc_40:
	; >>>>> Line:	125
	; >>>>> printString("Start Run and call scheduler\n"); 
	mov	ax, L_yakc_38
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	126
	; >>>>> run_flag = 1; 
	mov	byte [run_flag], 1
	; >>>>> Line:	127
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_yakc_39:
	push	bp
	mov	bp, sp
	jmp	L_yakc_40
	ALIGN	2
YKScheduler:
	; >>>>> Line:	130
	; >>>>> void YKScheduler(int save_flag){ 
	jmp	L_yakc_42
L_yakc_43:
	; >>>>> Line:	138
	; >>>>> highest_priority_task = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	139
	; >>>>> currentlyRunning = TKCurrently 
	mov	ax, word [TKCurrentlyRunning]
	mov	word [bp-4], ax
	; >>>>> Line:	141
	; >>>>> if(!run_flag || (TKCurrentlyRunning == highest_priority_task)){ 
	mov	al, byte [run_flag]
	test	al, al
	je	L_yakc_45
	mov	ax, word [bp-2]
	cmp	ax, word [TKCurrentlyRunning]
	jne	L_yakc_44
L_yakc_45:
	; >>>>> Line:	142
	; >>>>> return; 
	jmp	L_yakc_46
L_yakc_44:
	; >>>>> Line:	145
	; >>>>> YKCtxSwCount = YKCtxSwCount + 1; 
	mov	ax, word [YKCtxSwCount]
	inc	ax
	mov	word [YKCtxSwCount], ax
	; >>>>> Line:	146
	; >>>>> TKCurrentlyRunning = highest_priority_task; 
	mov	ax, word [bp-2]
	mov	word [TKCurrentlyRunning], ax
	; >>>>> Line:	147
	; >>>>> if(!save_flag){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_47
	; >>>>> Line:	149
	; >>>>> YKDispatcherNSave(highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	call	YKDispatcherNSave
	add	sp, 2
	jmp	L_yakc_48
L_yakc_47:
	; >>>>> Line:	154
	; >>>>> YKDispatcherSave(&(currentlyRunning->stackptr), highest_priority_task->stackptr); 
	mov	si, word [bp-2]
	push	word [si]
	push	word [bp-4]
	call	YKDispatcherSave
	add	sp, 4
L_yakc_48:
L_yakc_46:
	mov	sp, bp
	pop	bp
	ret
L_yakc_42:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_43
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	160
	; >>>>> void YKDelayTask(unsigned count){ 
	jmp	L_yakc_50
L_yakc_51:
	; >>>>> Line:	162
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	164
	; >>>>> if(count == 0){ 
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_yakc_52
	; >>>>> Line:	165
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	166
	; >>>>> return; 
	jmp	L_yakc_53
L_yakc_52:
	; >>>>> Line:	170
	; >>>>> ready = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	172
	; >>>>> + 1 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	173
	; >>>>> ready->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	175
	; >>>>> ready->next = YKDelayList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKDelayList]
	mov	word [si], ax
	; >>>>> Line:	176
	; >>>>> YKDelayList = ready; 
	mov	ax, word [bp-2]
	mov	word [YKDelayList], ax
	; >>>>> Line:	177
	; >>>>> ready->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	178
	; >>>>> if(ready->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_54
	; >>>>> Line:	179
	; >>>>> ready->next->prev=ready; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_54:
	; >>>>> Line:	181
	; >>>>> ready->delay = count; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	182
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	183
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_53:
	mov	sp, bp
	pop	bp
	ret
L_yakc_50:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_51
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	187
	; >>>>> void YKEnterISR(void){ 
	jmp	L_yakc_56
L_yakc_57:
	; >>>>> Line:	188
	; >>>>> YKISRDepth = YKISRDepth + 1; 
	mov	ax, word [YKISRDepth]
	inc	ax
	mov	word [YKISRDepth], ax
	mov	sp, bp
	pop	bp
	ret
L_yakc_56:
	push	bp
	mov	bp, sp
	jmp	L_yakc_57
	ALIGN	2
YKExitISR:
	; >>>>> Line:	192
	; >>>>> void YKExitISR(void){ 
	jmp	L_yakc_59
L_yakc_60:
	; >>>>> Line:	193
	; >>>>> YKISRDepth = YKISRDepth - 1; 
	mov	ax, word [YKISRDepth]
	dec	ax
	mov	word [YKISRDepth], ax
	; >>>>> Line:	195
	; >>>>> if(YKISRDepth == 0) { 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_61
	; >>>>> Line:	196
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_61:
	mov	sp, bp
	pop	bp
	ret
L_yakc_59:
	push	bp
	mov	bp, sp
	jmp	L_yakc_60
	ALIGN	2
YKTickHandler:
	; >>>>> Line:	200
	; >>>>> void YKTickHandler(void){ 
	jmp	L_yakc_63
L_yakc_64:
	; >>>>> Line:	203
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	204
	; >>>>> YKTickNum = YKTickNum + 1 
	mov	ax, word [YKTickNum]
	inc	ax
	mov	word [YKTickNum], ax
	; >>>>> Line:	205
	; >>>>> tempDelay = YKDelayList; 
	mov	ax, word [YKDelayList]
	mov	word [bp-2], ax
	; >>>>> Line:	207
	; >>>>> while(tempDelay != 0){ 
	jmp	L_yakc_66
L_yakc_65:
	; >>>>> Line:	208
	; >>>>> tempNext = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
	; >>>>> Line:	209
	; >>>>> tempDelay->delay = tempDelay->delay - 1; 
	mov	si, word [bp-2]
	add	si, 6
	mov	ax, word [si]
	dec	ax
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], ax
	; >>>>> Line:	210
	; >>>>> if(tempDelay->delay <= 0){ 
	mov	si, word [bp-2]
	add	si, 6
	cmp	word [si], 0
	jg	L_yakc_68
	; >>>>> Line:	212
	; >>>>> if(tempDelay->prev == 0){ 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_69
	; >>>>> Line:	213
	; >>>>> YKDelayList = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKDelayList], ax
	jmp	L_yakc_70
L_yakc_69:
	; >>>>> Line:	216
	; >>>>> tempDelay->prev->next = tempDelay->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	di, word [bp-2]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_70:
	; >>>>> Line:	218
	; >>>>> if(tempDelay->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_71
	; >>>>> Line:	219
	; >>>>> tempDelay->next->prev = tempDelay->prev; 
	mov	si, word [bp-2]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_71:
	; >>>>> Line:	222
	; >>>>> tempReady = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	223
	; >>>>> while(tempReady->priority < tempDelay->priority){ 
	jmp	L_yakc_73
L_yakc_72:
	; >>>>> Line:	224
	; >>>>> tempReady = tempR 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-4], ax
L_yakc_73:
	mov	si, word [bp-4]
	add	si, 4
	mov	di, word [bp-2]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_72
L_yakc_74:
	; >>>>> Line:	226
	; >>>>> if(tempReady->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_75
	; >>>>> Line:	227
	; >>>>> YKRdyList = tempDelay; 
	mov	ax, word [bp-2]
	mov	word [YKRdyList], ax
	jmp	L_yakc_76
L_yakc_75:
	; >>>>> Line:	230
	; >>>>> tempReady->prev->next = tempDelay; 
	mov	si, word [bp-4]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_76:
	; >>>>> Line:	233
	; >>>>> tempDelay->prev = tempReady->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-2]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	234
	; >>>>> tempDelay->next = tempReady; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	235
	; >>>>> tempReady->prev = tempDelay; 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_68:
	; >>>>> Line:	237
	; >>>>> tempDelay = tempNext; 
	mov	ax, word [bp-6]
	mov	word [bp-2], ax
L_yakc_66:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_65
L_yakc_67:
	; >>>>> Line:	239
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_63:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_64
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	242
	; >>>>> YKSEM* YKSemCreate(int initialValue){ 
	jmp	L_yakc_78
L_yakc_79:
	; >>>>> Line:	264
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	265
	; >>>>> i = 0; 
	mov	word [bp-2], 0
	; >>>>> Line:	266
	; >>>>> while(YKSemArray[i].active){ 
	jmp	L_yakc_81
L_yakc_80:
	; >>>>> Line:	267
	; >>>>> i = i+1; 
	mov	ax, word [bp-2]
	inc	ax
	mov	word [bp-2], ax
L_yakc_81:
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_80
L_yakc_82:
	; >>>>> Line:	271
	; >>>>> YKSemArray[i].active = 1; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 2
	mov	word [si], 1
	; >>>>> Line:	272
	; >>>>> YKSemArray[i].val = i 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	mov	si, ax
	add	si, YKSemArray
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	273
	; >>>>> YKSemArray[i].id = i; 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
	mov	si, ax
	add	si, 4
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	275
	; >>>>> return &(YKSemArray[i]); 
	mov	ax, word [bp-2]
	mov	cx, 6
	imul	cx
	add	ax, YKSemArray
L_yakc_83:
	mov	sp, bp
	pop	bp
	ret
L_yakc_78:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_79
	ALIGN	2
YKSemPend:
	; >>>>> Line:	285
	; >>>>> void YKSemPend(YKSEM *semaphore){ 
	jmp	L_yakc_85
L_yakc_86:
	; >>>>> Line:	332
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	333
	; >>>>> semaphore->val = semaphore->val - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	mov	word [si], ax
	; >>>>> Line:	334
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	336
	; >>>>> if (semaphore->val >= 0){ return; } 
	mov	si, word [bp+4]
	cmp	word [si], 0
	jl	L_yakc_87
	; >>>>> Line:	336
	; >>>>> if (semaphore->val >= 0){ return; } 
	jmp	L_yakc_88
L_yakc_87:
	; >>>>> Line:	338
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	339
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	; >>>>> Line:	340
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	341
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	342
	; >>>>> readyTask->next = YKSemWaitList; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [YKSemWaitList]
	mov	word [si], ax
	; >>>>> Line:	343
	; >>>>> YKSemWaitList = readyTask; 
	mov	ax, word [bp-2]
	mov	word [YKSemWaitList], ax
	; >>>>> Line:	344
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-2]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	346
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_89
	; >>>>> Line:	347
	; >>>>> readyTask->next->prev =  
	mov	si, word [bp-2]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-2]
	mov	word [si], ax
L_yakc_89:
	; >>>>> Line:	350
	; >>>>> readyTask->semWait = semaphore; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	352
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
	; >>>>> Line:	353
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_88:
	mov	sp, bp
	pop	bp
	ret
L_yakc_85:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_86
	ALIGN	2
YKSemPost:
	; >>>>> Line:	367
	; >>>>> void YKSemPost(YKSEM *semaphore){ 
	jmp	L_yakc_91
L_yakc_92:
	; >>>>> Line:	393
	; >>>>> unSuspTask = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	394
	; >>>>> semWaiting = YKSemWaitList; 
	mov	ax, word [YKSemWaitList]
	mov	word [bp-2], ax
	; >>>>> Line:	396
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	397
	; >>>>> semaphore->val = semaphore->val + 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	inc	ax
	mov	word [si], ax
	; >>>>> Line:	400
	; >>>>> while(semWaiting != 0){ 
	jmp	L_yakc_94
L_yakc_93:
	; >>>>> Line:	402
	; >>>>> if(semWaiting->semWait == semaphore){ 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_96
	; >>>>> Line:	403
	; >>>>> if((unSuspTask == 0) || (semWaiting->priority < unSuspTask->priority)){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_98
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_97
L_yakc_98:
	; >>>>> Line:	404
	; >>>>> unSuspTask = semWaiting; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
L_yakc_97:
L_yakc_96:
	; >>>>> Line:	407
	; >>>>> sk-> 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_94:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_93
L_yakc_95:
	; >>>>> Line:	410
	; >>>>> if(unSuspTask == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_99
	; >>>>> Line:	411
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	412
	; >>>>> return; 
	jmp	L_yakc_100
L_yakc_99:
	; >>>>> Line:	415
	; >>>>> if(unSuspTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_101
	; >>>>> Line:	416
	; >>>>> YKSemWaitList = unSuspTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKSemWaitList], ax
	jmp	L_yakc_102
L_yakc_101:
	; >>>>> Line:	419
	; >>>>> unSuspTask->prev->next = unSuspTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_102:
	; >>>>> Line:	422
	; >>>>> if (unSuspTask->next != 0){ 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_103
	; >>>>> Line:	423
	; >>>>> unSuspTask->next->prev = unSuspTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_103:
	; >>>>> Line:	427
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	428
	; >>>>> while (readyTask->priority < unSuspTask->priority){ 
	jmp	L_yakc_105
L_yakc_104:
	; >>>>> Line:	429
	; >>>>> readyTask = readyTask->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_105:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_104
L_yakc_106:
	; >>>>> Line:	431
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_107
	; >>>>> Line:	432
	; >>>>> YKRdyList = unSuspTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_108
L_yakc_107:
	; >>>>> Line:	435
	; >>>>> readyTask-> 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_108:
	; >>>>> Line:	437
	; >>>>> unSuspTask->prev = readyTask->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	438
	; >>>>> unSuspTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	439
	; >>>>> readyTask->prev = unSuspTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	441
	; >>>>> unSuspTask->semWait = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	443
	; >>>>> if( YKISRDepth == 0){ 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_109
	; >>>>> Line:	444
	; >>>>> YKScheduler(1); 
	mov	ax, 1
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_109:
	; >>>>> Line:	446
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_yakc_100:
	; >>>>> Line:	447
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_91:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_92
	ALIGN	2
queueInsert:
	; >>>>> Line:	450
	; >>>>> void queueInsert(YKQ* queue, void* msg){ 
	jmp	L_yakc_111
L_yakc_112:
	; >>>>> Line:	451
	; >>>>> queue->base_addr[queue->head] = msg; 
	mov	si, word [bp+4]
	add	si, 6
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	452
	; >>>>> if(queue->head < queue->size){ 
	mov	si, word [bp+4]
	add	si, 6
	mov	di, word [bp+4]
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_113
	; >>>>> Line:	453
	; >>>>> queue->head += 1; 
	mov	si, word [bp+4]
	add	si, 6
	inc	word [si]
	jmp	L_yakc_114
L_yakc_113:
	; >>>>> Line:	456
	; >>>>> queue->head = 0; 
	mov	si, word [bp+4]
	add	si, 6
	mov	word [si], 0
L_yakc_114:
	mov	sp, bp
	pop	bp
	ret
L_yakc_111:
	push	bp
	mov	bp, sp
	jmp	L_yakc_112
	ALIGN	2
queueRemove:
	; >>>>> Line:	460
	; >>>>> void* queueRemove(YKQ* queue){ 
	jmp	L_yakc_116
L_yakc_117:
	; >>>>> Line:	462
	; >>>>> msg = queue->base_addr[queue->tail]; 
	mov	si, word [bp+4]
	add	si, 8
	mov	ax, word [si]
	shl	ax, 1
	mov	si, ax
	mov	di, word [bp+4]
	add	di, 4
	add	si, word [di]
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	463
	; >>>>> if(queue->tail 
	mov	si, word [bp+4]
	add	si, 8
	cmp	word [si], 0
	jle	L_yakc_118
	; >>>>> Line:	464
	; >>>>> queue->head -= 1; 
	mov	si, word [bp+4]
	add	si, 6
	dec	word [si]
	jmp	L_yakc_119
L_yakc_118:
	; >>>>> Line:	467
	; >>>>> queue->head = queue->size - 1; 
	mov	si, word [bp+4]
	mov	ax, word [si]
	dec	ax
	add	si, 6
	mov	word [si], ax
L_yakc_119:
	; >>>>> Line:	469
	; >>>>> return msg; 
	mov	ax, word [bp-2]
L_yakc_120:
	mov	sp, bp
	pop	bp
	ret
L_yakc_116:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_117
	ALIGN	2
YKQCreate:
	; >>>>> Line:	473
	; >>>>> YKQ *YKQCreate(void **start, unsigned size){ 
	jmp	L_yakc_122
L_yakc_123:
	; >>>>> Line:	475
	; >>>>> queue->base_addr = start; 
	mov	si, word [bp-2]
	add	si, 4
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	476
	; >>>>> queue->cur_length = 0; 
	mov	si, word [bp-2]
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	477
	; >>>>> queue->size = size; 
	mov	si, word [bp-2]
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	478
	; >>>>> queue->tail = 0; 
	mov	si, word [bp-2]
	add	si, 8
	mov	word [si], 0
	; >>>>> Line:	479
	; >>>>> queue->head = 0; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	481
	; >>>>> return queue; 
	mov	ax, word [bp-2]
L_yakc_124:
	mov	sp, bp
	pop	bp
	ret
L_yakc_122:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_123
	ALIGN	2
YKQPend:
	; >>>>> Line:	490
	; >>>>> void *YKQPend(YKQ *queue){ 
	jmp	L_yakc_126
L_yakc_127:
	; >>>>> Line:	494
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	495
	; >>>>> if(queue->cur_length == 0){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_128
	; >>>>> Line:	497
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	498
	; >>>>> YKRdyList = readyTask->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	499
	; >>>>> readyTask->next->prev = 0; 
	mov	si, word [bp-6]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	500
	; >>>>> _lengt 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [YKQWaitList]
	mov	word [si], ax
	; >>>>> Line:	501
	; >>>>> YKQWaitList = readyTask; 
	mov	ax, word [bp-6]
	mov	word [YKQWaitList], ax
	; >>>>> Line:	502
	; >>>>> readyTask->prev = 0; 
	mov	si, word [bp-6]
	add	si, 10
	mov	word [si], 0
	; >>>>> Line:	504
	; >>>>> if(readyTask->next != 0){ 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_129
	; >>>>> Line:	505
	; >>>>> readyTask->next->prev = readyTask; 
	mov	si, word [bp-6]
	add	si, 8
	mov	si, word [si]
	add	si, 10
	mov	ax, word [bp-6]
	mov	word [si], ax
L_yakc_129:
	; >>>>> Line:	508
	; >>>>> readyTask->queueWait = queue; 
	mov	si, word [bp-6]
	add	si, 14
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	510
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	511
	; >>>>> return 0; 
	xor	ax, ax
	jmp	L_yakc_130
	jmp	L_yakc_131
L_yakc_128:
	; >>>>> Line:	514
	; >>>>> msg = queueRemove(queue); 
	push	word [bp+4]
	call	queueRemove
	add	sp, 2
	mov	word [bp-4], ax
	; >>>>> Line:	515
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	516
	; >>>>> return msg; 
	mov	ax, word [bp-4]
L_yakc_131:
L_yakc_130:
	mov	sp, bp
	pop	bp
	ret
L_yakc_126:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_127
L_yakc_135:
	DB	" ",0
L_yakc_134:
	DB	"Whoops, dont post it",0
L_yakc_133:
	DB	"Post it",0
	ALIGN	2
YKQPost:
	; >>>>> Line:	532
	; >>>>> int YKQPost(YKQ *queue, void *msg){ 
	jmp	L_yakc_136
L_yakc_137:
	; >>>>> Line:	534
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	536
	; >>>>> if(queue->cur_length < queue->size){ 
	mov	si, word [bp+4]
	add	si, 2
	mov	di, word [bp+4]
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_138
	; >>>>> Line:	537
	; >>>>> printString("Post it"); 
	mov	ax, L_yakc_133
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	538
	; >>>>> queue->cur_lengt 
	mov	si, word [bp+4]
	add	si, 2
	inc	word [si]
	; >>>>> Line:	540
	; >>>>> queueInsert(queue, msg); 
	push	word [bp+6]
	push	word [bp+4]
	call	queueInsert
	add	sp, 4
	; >>>>> Line:	541
	; >>>>> queueWait = YKQWaitList; 
	mov	ax, word [YKQWaitList]
	mov	word [bp-2], ax
	; >>>>> Line:	542
	; >>>>> unWaitTask = 0; 
	mov	word [bp-4], 0
	; >>>>> Line:	544
	; >>>>> while(queueWait != 0){ 
	jmp	L_yakc_140
L_yakc_139:
	; >>>>> Line:	546
	; >>>>> if(queueWait->queueWait == queue){ 
	mov	si, word [bp-2]
	add	si, 14
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_142
	; >>>>> Line:	547
	; >>>>> if((unWaitTask == 0) || (queueWait->priority < unWaitTask->priority)){ 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_144
	mov	si, word [bp-2]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jle	L_yakc_143
L_yakc_144:
	; >>>>> Line:	548
	; >>>>> unWaitTask = queueWait; 
	mov	ax, word [bp-2]
	mov	word [bp-4], ax
L_yakc_143:
L_yakc_142:
	; >>>>> Line:	551
	; >>>>> queueWait = queueWait->next; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_140:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_139
L_yakc_141:
	; >>>>> Line:	555
	; >>>>> if(unWaitTask == 0){ 
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_145
	; >>>>> Line:	556
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	557
	; >>>>> return 1; 
	mov	ax, 1
	jmp	L_yakc_146
L_yakc_145:
	; >>>>> Line:	561
	; >>>>> if(unWaitTask->prev == 0){ 
	mov	si, word [bp-4]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_147
	; >>>>> Line:	562
	; >>>>> YKQWaitList = unWaitTask->next; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	mov	word [YKQWaitList], ax
	jmp	L_yakc_148
L_yakc_147:
	; >>>>> Line:	565
	; >>>>> unWaitTask->prev->nex 
	mov	si, word [bp-4]
	add	si, 8
	mov	di, word [bp-4]
	add	di, 10
	mov	di, word [di]
	add	di, 8
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_148:
	; >>>>> Line:	568
	; >>>>> if (unWaitTask->next != 0){ 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_149
	; >>>>> Line:	569
	; >>>>> unWaitTask->next->prev = unWaitTask->prev; 
	mov	si, word [bp-4]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 8
	mov	di, word [di]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_149:
	; >>>>> Line:	573
	; >>>>> readyTask = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-6], ax
	; >>>>> Line:	574
	; >>>>> while (readyTask->priority < unWaitTask->priority){ 
	jmp	L_yakc_151
L_yakc_150:
	; >>>>> Line:	575
	; >>>>> readyTask = readyTask->next; 
	mov	si, word [bp-6]
	add	si, 8
	mov	ax, word [si]
	mov	word [bp-6], ax
L_yakc_151:
	mov	si, word [bp-6]
	add	si, 4
	mov	di, word [bp-4]
	add	di, 4
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_150
L_yakc_152:
	; >>>>> Line:	577
	; >>>>> if(readyTask->prev == 0){ 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [si]
	test	ax, ax
	jne	L_yakc_153
	; >>>>> Line:	578
	; >>>>> YKRdyList = unWaitTask; 
	mov	ax, word [bp-4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_154
L_yakc_153:
	; >>>>> Line:	581
	; >>>>> readyTask->prev->next = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	si, word [si]
	add	si, 8
	mov	ax, word [bp-4]
	mov	word [si], ax
L_yakc_154:
	; >>>>> Line:	583
	; >>>>> unWaitTask->prev = readyTask->prev; 
	mov	si, word [bp-6]
	add	si, 10
	mov	di, word [bp-4]
	add	di, 10
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	584
	; >>>>> unWaitTask->next = readyTask; 
	mov	si, word [bp-4]
	add	si, 8
	mov	ax, word [bp-6]
	mov	word [si], ax
	; >>>>> Line:	585
	; >>>>> readyTask->prev = unWaitTask; 
	mov	si, word [bp-6]
	add	si, 10
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	587
	; >>>>> unWaitTask->semWait = 0; 
	mov	si, word [bp-4]
	add	si, 12
	mov	word [si], 0
	; >>>>> Line:	589
	; >>>>> if( 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_155
	; >>>>> Line:	590
	; >>>>> YKScheduler(0); 
	xor	ax, ax
	push	ax
	call	YKScheduler
	add	sp, 2
L_yakc_155:
	; >>>>> Line:	592
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	593
	; >>>>> return 1; 
	mov	ax, 1
	jmp	L_yakc_146
	jmp	L_yakc_156
L_yakc_138:
	; >>>>> Line:	596
	; >>>>> printString("Whoops, dont post it"); 
	mov	ax, L_yakc_134
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	597
	; >>>>> printInt(queue->cur_length); 
	mov	si, word [bp+4]
	add	si, 2
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	598
	; >>>>> printString(" "); 
	mov	ax, L_yakc_135
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	599
	; >>>>> printInt(queue->size); 
	mov	si, word [bp+4]
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	600
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	601
	; >>>>> return 0; 
	xor	ax, ax
L_yakc_156:
L_yakc_146:
	mov	sp, bp
	pop	bp
	ret
L_yakc_136:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_137
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKDelayList:
	TIMES	2 db 0
YKSemWaitList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	160 db 0
idleStack:
	TIMES	512 db 0
YKISRDepth:
	TIMES	2 db 0
YKSemArray:
	TIMES	114 db 0
YKQWaitList:
	TIMES	2 db 0
TKCurrentlyRunning:
	TIMES	2 db 0
